import { JafrLetterDetail, JafrSymbolPreset } from '../types';

export const JAFR_28_LETTERS_DATA: Record<string, JafrLetterDetail> = {
  'ا': {
    letter: 'ا',
    name: 'الف',
    abjadKabir: 1,
    abjadSaghir: 1,
    abjadWasit: 1,
    abjadAkbar: 1,
    element: 'fire',
    elementUrdu: 'آتشی (گرم و خشک)',
    nature: 'گرم و خشک (مرتبہ اول)',
    planet: 'Sun',
    planetUrdu: 'شمس (سورج)',
    lunarMansion: {
      number: 1,
      name: 'الشرطین (Al-Sharatain)',
      degree: 'حمل ۰° تا ۱۲°۵۱\'',
      spiritualEffect: 'بنیاد، ابتدا، شجاعت اور نصرت کے اعمال'
    },
    nazeerah: 'س',
    nazeerahAbjad: 60,
    oppositeElement: 'آبی (سرد و تر)',
    isNourani: true,
    isSowamat: true,
    pronunciationType: 'ملفوظی',
    muwakkil: 'اسرافیل ؑ / روقیائیل',
    awan: 'المذہب (حاکم روزِ یکشنبہ)',
    metal: 'خالص سونا (Gold)',
    color: 'روشن زرد و سرخ طلائی',
    incense: 'عود و صندل سرخ و لبان ذکر',
    bodyPart: 'سر، دماغ اور آنکھیں'
  },
  'ب': {
    letter: 'ب',
    name: 'باء',
    abjadKabir: 2,
    abjadSaghir: 2,
    abjadWasit: 2,
    abjadAkbar: 2,
    element: 'air',
    elementUrdu: 'بادی (گرم و تر)',
    nature: 'گرم و تر (مرتبہ اول)',
    planet: 'Moon',
    planetUrdu: 'قمر (چاند)',
    lunarMansion: {
      number: 2,
      name: 'البطین (Al-Butain)',
      degree: 'حمل ۱۲°۵۱\' تا ۲۵°۴۲\'',
      spiritualEffect: 'تولید، الفت، قلبی کشش اور دفائن کا انکشاف'
    },
    nazeerah: 'ع',
    nazeerahAbjad: 70,
    oppositeElement: 'خاکی (سرد و خشک)',
    isNourani: false,
    isSowamat: false,
    pronunciationType: 'ملبوبی',
    muwakkil: 'جبرائیل ؑ / جبرائیل علوی',
    awan: 'مرّة (حاکم روزِ دوشنبہ)',
    metal: 'خالص چاندی (Silver)',
    color: 'سفید چمکدار و نقرئی',
    incense: 'کافور و صندل سفید و عرق گلاب',
    bodyPart: 'سینہ، پھیپھڑے اور نظام تنفس'
  },
  'ج': {
    letter: 'ج',
    name: 'جیم',
    abjadKabir: 3,
    abjadSaghir: 3,
    abjadWasit: 3,
    abjadAkbar: 3,
    element: 'water',
    elementUrdu: 'آبی (سرد و تر)',
    nature: 'سرد و تر (مرتبہ اول)',
    planet: 'Mars',
    planetUrdu: 'مریخ (بہام)',
    lunarMansion: {
      number: 3,
      name: 'الثریا (Al-Thurayya)',
      degree: 'ثور ۰° تا ۱۲°۵۱\'',
      spiritualEffect: 'محبت، دولت، تسخیر قلوب اور خیر و برکت'
    },
    nazeerah: 'ف',
    nazeerahAbjad: 80,
    oppositeElement: 'آتشی (گرم و خشک)',
    isNourani: false,
    isSowamat: false,
    pronunciationType: 'ملفوظی',
    muwakkil: 'سمسمائیل ؑ',
    awan: 'الاحمر (حاکم روزِ سہ شنبہ)',
    metal: 'خالص لوہا و فولاد (Iron/Steel)',
    color: 'گہرا لال و آتشیں سرخ',
    incense: 'حرمل و مصطگی و گندھک',
    bodyPart: 'پیٹ، معدہ اور نظام انہضام'
  },
  'د': {
    letter: 'د',
    name: 'دال',
    abjadKabir: 4,
    abjadSaghir: 4,
    abjadWasit: 4,
    abjadAkbar: 4,
    element: 'earth',
    elementUrdu: 'خاکی (سرد و خشک)',
    nature: 'سرد و خشک (مرتبہ اول)',
    planet: 'Mercury',
    planetUrdu: 'عطارد (تیر)',
    lunarMansion: {
      number: 4,
      name: 'الدبران (Al-Dabaran)',
      degree: 'ثور ۱۲°۵۱\' تا ۲۵°۴۲\'',
      spiritualEffect: 'عقد اللسان، رکاوٹ اور تفریق اعداء'
    },
    nazeerah: 'ص',
    nazeerahAbjad: 90,
    oppositeElement: 'بادی (گرم و تر)',
    isNourani: false,
    isSowamat: true,
    pronunciationType: 'ملفوظی',
    muwakkil: 'میکائیل ؑ',
    awan: 'برقان (حاکم روزِ چہار شنبہ)',
    metal: 'پارہ و کانسی (Mercury/Bronze)',
    color: 'سبز زمردی و خاکی',
    incense: 'جاوتری و لونگ و لبان',
    bodyPart: 'پاؤں، پنڈلیاں اور جوڑ'
  },
  'ہ': {
    letter: 'ہ',
    name: 'ھاء',
    abjadKabir: 5,
    abjadSaghir: 5,
    abjadWasit: 5,
    abjadAkbar: 5,
    element: 'fire',
    elementUrdu: 'آتشی (گرم و خشک)',
    nature: 'گرم و خشک (مرتبہ دوم)',
    planet: 'Jupiter',
    planetUrdu: 'مشتری (برجیس)',
    lunarMansion: {
      number: 5,
      name: 'الهقعة (Al-Haq\'ah)',
      degree: 'جوزا ۰° تا ۱۲°۵۱\'',
      spiritualEffect: 'علم، حکمت، مسافرت اور صلح و آشتی'
    },
    nazeerah: 'ق',
    nazeerahAbjad: 100,
    oppositeElement: 'آبی (سرد و تر)',
    isNourani: true,
    isSowamat: true,
    pronunciationType: 'ملبوبی',
    muwakkil: 'صرفیائیل ؑ',
    awan: 'شمهورش (حاکم روزِ پنجشنبہ)',
    metal: 'پیتل و قلعی (Brass/Tin)',
    color: 'نیلا آسمانی و فیروزی',
    incense: 'عنبر و مشک و زعفران خالص',
    bodyPart: 'گلا، گردن اور آواز'
  },
  'و': {
    letter: 'و',
    name: 'واؤ',
    abjadKabir: 6,
    abjadSaghir: 6,
    abjadWasit: 6,
    abjadAkbar: 6,
    element: 'air',
    elementUrdu: 'بادی (گرم و تر)',
    nature: 'گرم و تر (مرتبہ دوم)',
    planet: 'Venus',
    planetUrdu: 'زہرہ (ناہید)',
    lunarMansion: {
      number: 6,
      name: 'الهنعة (Al-Han\'ah)',
      degree: 'جوزا ۱۲°۵۱\' تا ۲۵°۴۲\'',
      spiritualEffect: 'محبت، دوستی، زناشوئی الفت اور حسن و جمال'
    },
    nazeerah: 'ر',
    nazeerahAbjad: 200,
    oppositeElement: 'خاکی (سرد و خشک)',
    isNourani: false,
    isSowamat: true,
    pronunciationType: 'مسروری',
    muwakkil: 'عنیائیل ؑ',
    awan: 'زوبعة / ابیض (حاکم روزِ آدینہ)',
    metal: 'تانبا (Copper)',
    color: 'گلابی و زعفرانی چمکیلا',
    incense: 'صندل و عطر چنبیلی و مستکی',
    bodyPart: 'گردن، پسلیاں اور بال'
  },
  'ز': {
    letter: 'ز',
    name: 'زاء',
    abjadKabir: 7,
    abjadSaghir: 7,
    abjadWasit: 7,
    abjadAkbar: 7,
    element: 'water',
    elementUrdu: 'آبی (سرد و تر)',
    nature: 'سرد و تر (مرتبہ دوم)',
    planet: 'Saturn',
    planetUrdu: 'زحل (کیوان)',
    lunarMansion: {
      number: 7,
      name: 'الذراع (Al-Dhira)',
      degree: 'سرطان ۰° تا ۱۲°۵۱\'',
      spiritualEffect: 'برکت، فراخی رزق، زراعت اور حفاظت'
    },
    nazeerah: 'ش',
    nazeerahAbjad: 300,
    oppositeElement: 'آتشی (گرم و خشک)',
    isNourani: false,
    isSowamat: false,
    pronunciationType: 'ملبوبی',
    muwakkil: 'کسفیائیل ؑ',
    awan: 'میمون السحاب (حاکم روزِ شنبہ)',
    metal: 'سیسہ و کالا لوہا (Lead)',
    color: 'سیاہ و سرمئی تاریک',
    incense: 'صبر، حلتیک (ہینگ) و لبان اسود',
    bodyPart: 'پشت، ریڑھ کی ہڈی'
  },
  'ح': {
    letter: 'ح',
    name: 'حاء',
    abjadKabir: 8,
    abjadSaghir: 8,
    abjadWasit: 8,
    abjadAkbar: 8,
    element: 'earth',
    elementUrdu: 'خاکی (سرد و خشک)',
    nature: 'سرد و خشک (مرتبہ دوم)',
    planet: 'Sun',
    planetUrdu: 'شمس (سورج)',
    lunarMansion: {
      number: 8,
      name: 'النثرة (Al-Nathrah)',
      degree: 'سرطان ۱۲°۵۱\' تا ۲۵°۴۲\'',
      spiritualEffect: 'شفائے امراض، تسکین درد اور دافعِ زہر'
    },
    nazeerah: 'ت',
    nazeerahAbjad: 400,
    oppositeElement: 'بادی (گرم و تر)',
    isNourani: true,
    isSowamat: true,
    pronunciationType: 'ملبوبی',
    muwakkil: 'روقیائیل ؑ',
    awan: 'المذہب',
    metal: 'سونا (Gold)',
    color: 'سنہری شاندار',
    incense: 'عود و مشک و لبان ذکر',
    bodyPart: 'دل، سینے کا مرکز'
  },
  'ط': {
    letter: 'ط',
    name: 'طاء',
    abjadKabir: 9,
    abjadSaghir: 9,
    abjadWasit: 9,
    abjadAkbar: 9,
    element: 'fire',
    elementUrdu: 'آتشی (گرم و خشک)',
    nature: 'گرم و خشک (مرتبہ سوم)',
    planet: 'Moon',
    planetUrdu: 'قمر (چاند)',
    lunarMansion: {
      number: 9,
      name: 'الطرف (Al-Tarf)',
      degree: 'اسد ۰° تا ۱۲°۵۱\'',
      spiritualEffect: 'آنکھوں کی روشنی، کشف اور نگاہ کی حفاظت'
    },
    nazeerah: 'ث',
    nazeerahAbjad: 500,
    oppositeElement: 'آبی (سرد و تر)',
    isNourani: true,
    isSowamat: true,
    pronunciationType: 'ملبوبی',
    muwakkil: 'جبرائیل ؑ',
    awan: 'مرّة',
    metal: 'چاندی (Silver)',
    color: 'نقری و درخشاں',
    incense: 'کافور و گلاب',
    bodyPart: 'پھیپھڑے و تنفس'
  },
  'ی': {
    letter: 'ی',
    name: 'یاء',
    abjadKabir: 10,
    abjadSaghir: 1,
    abjadWasit: 1,
    abjadAkbar: 10,
    element: 'air',
    elementUrdu: 'بادی (گرم و تر)',
    nature: 'گرم و تر (مرتبہ سوم)',
    planet: 'Mars',
    planetUrdu: 'مریخ (بہام)',
    lunarMansion: {
      number: 10,
      name: 'الجبهة (Al-Jabhah)',
      degree: 'اسد ۱۲°۵۱\' تا ۲۵°۴۲\'',
      spiritualEffect: 'ہیبت، غلبہ، رعب اور امراء پر اثر پذیری'
    },
    nazeerah: 'خ',
    nazeerahAbjad: 600,
    oppositeElement: 'خاکی (سرد و خشک)',
    isNourani: true,
    isSowamat: false,
    pronunciationType: 'ملبوبی',
    muwakkil: 'سمسمائیل ؑ',
    awan: 'الاحمر',
    metal: 'فولاد (Steel)',
    color: 'لال عقیقی',
    incense: 'حرمل و رائی',
    bodyPart: 'دونوں ہاتھ اور انگلیاں'
  },
  'ک': {
    letter: 'ک',
    name: 'کاف',
    abjadKabir: 20,
    abjadSaghir: 2,
    abjadWasit: 2,
    abjadAkbar: 20,
    element: 'water',
    elementUrdu: 'آبی (سرد و تر)',
    nature: 'سرد و تر (مرتبہ سوم)',
    planet: 'Mercury',
    planetUrdu: 'عطارد (تیر)',
    lunarMansion: {
      number: 11,
      name: 'الزبرة (Al-Zubrah)',
      degree: 'سنبلہ ۰° تا ۱۲°۵۱\'',
      spiritualEffect: 'حصولِ مقاصد، تسخیرِ خلق اور کشادگی'
    },
    nazeerah: 'ذ',
    nazeerahAbjad: 700,
    oppositeElement: 'آتشی (گرم و خشک)',
    isNourani: true,
    isSowamat: true,
    pronunciationType: 'ملفوظی',
    muwakkil: 'میکائیل ؑ',
    awan: 'برقان',
    metal: 'پارہ و برونز',
    color: 'سبز پستہ رنگ',
    incense: 'جاوتری و لونگ',
    bodyPart: 'دونوں بازو اور کندھے'
  },
  'ل': {
    letter: 'ل',
    name: 'لام',
    abjadKabir: 30,
    abjadSaghir: 3,
    abjadWasit: 3,
    abjadAkbar: 30,
    element: 'earth',
    elementUrdu: 'خاکی (سرد و خشک)',
    nature: 'سرد و خشک (مرتبہ سوم)',
    planet: 'Jupiter',
    planetUrdu: 'مشتری (برجیس)',
    lunarMansion: {
      number: 12,
      name: 'الصرفة (Al-Sarfah)',
      degree: 'سنبلہ ۱۲°۵۱\' تا ۲۵°۴۲\'',
      spiritualEffect: 'رزق، زراعت، فضل الٰہی اور علمِ باطن'
    },
    nazeerah: 'ض',
    nazeerahAbjad: 800,
    oppositeElement: 'بادی (گرم و تر)',
    isNourani: true,
    isSowamat: true,
    pronunciationType: 'ملفوظی',
    muwakkil: 'صرفیائیل ؑ',
    awan: 'شمهورش',
    metal: 'پیتل',
    color: 'نیلا فیروزی',
    incense: 'عنبر و زعفران',
    bodyPart: 'رانیں اور گھٹنے'
  },
  'م': {
    letter: 'م',
    name: 'میم',
    abjadKabir: 40,
    abjadSaghir: 4,
    abjadWasit: 4,
    abjadAkbar: 40,
    element: 'fire',
    elementUrdu: 'آتشی (گرم و خشک)',
    nature: 'گرم و خشک (مرتبہ چہارم)',
    planet: 'Venus',
    planetUrdu: 'زہرہ (ناہید)',
    lunarMansion: {
      number: 13,
      name: 'العواء (Al-Awwa)',
      degree: 'میزان ۰° تا ۱۲°۵۱\'',
      spiritualEffect: 'الفت، نکاح، صلح اور تسخیرِ خاص'
    },
    nazeerah: 'ظ',
    nazeerahAbjad: 900,
    oppositeElement: 'آبی (سرد و تر)',
    isNourani: true,
    isSowamat: true,
    pronunciationType: 'مسروری',
    muwakkil: 'عنیائیل ؑ',
    awan: 'زوبعة',
    metal: 'تانبا',
    color: 'گلابی شفق',
    incense: 'صندل و گلاب و لبان',
    bodyPart: 'چہرہ، جبین اور ہونٹ'
  },
  'ن': {
    letter: 'ن',
    name: 'نون',
    abjadKabir: 50,
    abjadSaghir: 5,
    abjadWasit: 5,
    abjadAkbar: 50,
    element: 'air',
    elementUrdu: 'بادی (گرم و تر)',
    nature: 'گرم و تر (مرتبہ چہارم)',
    planet: 'Saturn',
    planetUrdu: 'زحل (کیوان)',
    lunarMansion: {
      number: 14,
      name: 'السماك (Al-Simak)',
      degree: 'میزان ۱۲°۵۱\' تا ۲۵°۴۲\'',
      spiritualEffect: 'تحفظ، دافعِ سحر، دفعِ دشمن اور سلامتی'
    },
    nazeerah: 'غ',
    nazeerahAbjad: 1000,
    oppositeElement: 'خاکی (سرد و خشک)',
    isNourani: true,
    isSowamat: false,
    pronunciationType: 'مسروری',
    muwakkil: 'کسفیائیل ؑ',
    awan: 'میمون',
    metal: 'سیسہ',
    color: 'سیاہ نیلا',
    incense: 'صبر و حلتیک',
    bodyPart: 'ناک اور حسِ شامہ'
  },
  'س': {
    letter: 'س',
    name: 'سین',
    abjadKabir: 60,
    abjadSaghir: 6,
    abjadWasit: 6,
    abjadAkbar: 60,
    element: 'water',
    elementUrdu: 'آبی (سرد و تر)',
    nature: 'سرد و تر (مرتبہ چہارم)',
    planet: 'Sun',
    planetUrdu: 'شمس (سورج)',
    lunarMansion: {
      number: 15,
      name: 'الغفر (Al-Ghafr)',
      degree: 'عقرب ۰° تا ۱۲°۵۱\'',
      spiritualEffect: 'اختفاء، پردہ پوشی، حفاظت از اعداء اور امن'
    },
    nazeerah: 'ا',
    nazeerahAbjad: 1,
    oppositeElement: 'آتشی (گرم و خشک)',
    isNourani: true,
    isSowamat: true,
    pronunciationType: 'ملفوظی',
    muwakkil: 'روقیائیل ؑ',
    awan: 'المذہب',
    metal: 'سونا',
    color: 'طلائی چمکدار',
    incense: 'عود و صندل سرخ',
    bodyPart: 'آنکھیں اور بینائی'
  },
  'ع': {
    letter: 'ع',
    name: 'عین',
    abjadKabir: 70,
    abjadSaghir: 7,
    abjadWasit: 7,
    abjadAkbar: 70,
    element: 'earth',
    elementUrdu: 'خاکی (سرد و خشک)',
    nature: 'سرد و خشک (مرتبہ چہارم)',
    planet: 'Moon',
    planetUrdu: 'قمر (چاند)',
    lunarMansion: {
      number: 16,
      name: 'الزبانا (Al-Zubana)',
      degree: 'عقرب ۱۲°۵۱\' تا ۲۵°۴۲\'',
      spiritualEffect: 'کشفِ باطن، نورِ قلب، بینائی اور تجارت'
    },
    nazeerah: 'ب',
    nazeerahAbjad: 2,
    oppositeElement: 'بادی (گرم و تر)',
    isNourani: true,
    isSowamat: true,
    pronunciationType: 'ملفوظی',
    muwakkil: 'جبرائیل ؑ',
    awan: 'مرّة',
    metal: 'چاندی',
    color: 'چاندی جیسا سفید',
    incense: 'کافور و لبان',
    bodyPart: 'کان اور قوتِ سماعت'
  },
  'ف': {
    letter: 'ف',
    name: 'فاء',
    abjadKabir: 80,
    abjadSaghir: 8,
    abjadWasit: 8,
    abjadAkbar: 80,
    element: 'fire',
    elementUrdu: 'آتشی (گرم و خشک)',
    nature: 'گرم و خشک (مرتبہ پنجم)',
    planet: 'Mars',
    planetUrdu: 'مریخ (بہام)',
    lunarMansion: {
      number: 17,
      name: 'الإكليل (Al-Ikleel)',
      degree: 'قوس ۰° تا ۱۲°۵۱\'',
      spiritualEffect: 'فتح، نصرت، غلبہ بر اعداء اور ہیبت'
    },
    nazeerah: 'ج',
    nazeerahAbjad: 3,
    oppositeElement: 'آبی (سرد و تر)',
    isNourani: false,
    isSowamat: false,
    pronunciationType: 'ملبوبی',
    muwakkil: 'سمسمائیل ؑ',
    awan: 'الاحمر',
    metal: 'فولاد',
    color: 'سرخ گہرا',
    incense: 'حرمل و رائی',
    bodyPart: 'زبان اور قوتِ گویائی'
  },
  'ص': {
    letter: 'ص',
    name: 'صاد',
    abjadKabir: 90,
    abjadSaghir: 9,
    abjadWasit: 9,
    abjadAkbar: 90,
    element: 'air',
    elementUrdu: 'بادی (گرم و تر)',
    nature: 'گرم و تر (مرتبہ پنجم)',
    planet: 'Mercury',
    planetUrdu: 'عطارد (تیر)',
    lunarMansion: {
      number: 18,
      name: 'القلب (Al-Qalb)',
      degree: 'قوس ۱۲°۵۱\' تا ۲۵°۴۲\'',
      spiritualEffect: 'تسخیرِ قلوب، صفائے باطن اور دافعِ وساوس'
    },
    nazeerah: 'د',
    nazeerahAbjad: 4,
    oppositeElement: 'خاکی (سرد و خشک)',
    isNourani: true,
    isSowamat: true,
    pronunciationType: 'ملفوظی',
    muwakkil: 'میکائیل ؑ',
    awan: 'برقان',
    metal: 'پارہ و کانسی',
    color: 'سبز طوطی',
    incense: 'جاوتری و لونگ',
    bodyPart: 'گردے اور مثانہ'
  },
  'ق': {
    letter: 'ق',
    name: 'قاف',
    abjadKabir: 100,
    abjadSaghir: 1,
    abjadWasit: 10,
    abjadAkbar: 100,
    element: 'water',
    elementUrdu: 'آبی (سرد و تر)',
    nature: 'سرد و تر (مرتبہ پنجم)',
    planet: 'Jupiter',
    planetUrdu: 'مشتری (برجیس)',
    lunarMansion: {
      number: 19,
      name: 'الشولة (Al-Shaulah)',
      degree: 'جدی ۰° تا ۱۲°۵۱\'',
      spiritualEffect: 'قہر، دافعِ موذی جانور اور قفلِ شرور'
    },
    nazeerah: 'ہ',
    nazeerahAbjad: 5,
    oppositeElement: 'آتشی (گرم و خشک)',
    isNourani: true,
    isSowamat: false,
    pronunciationType: 'ملفوظی',
    muwakkil: 'صرفیائیل ؑ',
    awan: 'شمهورش',
    metal: 'پیتل و قلعی',
    color: 'آسمانی روشن',
    incense: 'عنبر و زعفران',
    bodyPart: 'مثانہ اور مجاری البول'
  },
  'ر': {
    letter: 'ر',
    name: 'راء',
    abjadKabir: 200,
    abjadSaghir: 2,
    abjadWasit: 20,
    abjadAkbar: 200,
    element: 'earth',
    elementUrdu: 'خاکی (سرد و خشک)',
    nature: 'سرد و خشک (مرتبہ پنجم)',
    planet: 'Venus',
    planetUrdu: 'زہرہ (ناہید)',
    lunarMansion: {
      number: 20,
      name: 'النعائم (Al-Na\'aim)',
      degree: 'جدی ۱۲°۵۱\' تا ۲۵°۴۲\'',
      spiritualEffect: 'سعادت، فراخیِ رزق، زراعت اور قبولیت'
    },
    nazeerah: 'و',
    nazeerahAbjad: 6,
    oppositeElement: 'بادی (گرم و تر)',
    isNourani: true,
    isSowamat: true,
    pronunciationType: 'ملبوبی',
    muwakkil: 'عنیائیل ؑ',
    awan: 'زوبعة',
    metal: 'تانبا',
    color: 'گلابی و زعفرانی',
    incense: 'صندل و عطر چنبیلی',
    bodyPart: 'جگر اور تلی'
  },
  'ش': {
    letter: 'ش',
    name: 'شین',
    abjadKabir: 300,
    abjadSaghir: 3,
    abjadWasit: 30,
    abjadAkbar: 300,
    element: 'fire',
    elementUrdu: 'آتشی (گرم و خشک)',
    nature: 'گرم و خشک (مرتبہ ششم)',
    planet: 'Saturn',
    planetUrdu: 'زحل (کیوان)',
    lunarMansion: {
      number: 21,
      name: 'البلدة (Al-Baldah)',
      degree: 'دلو ۰° تا ۱۲°۵۱\'',
      spiritualEffect: 'تعمیر، مکان، آبادی اور مسافرت'
    },
    nazeerah: 'ز',
    nazeerahAbjad: 7,
    oppositeElement: 'آبی (سرد و تر)',
    isNourani: false,
    isSowamat: false,
    pronunciationType: 'ملفوظی',
    muwakkil: 'کسفیائیل ؑ',
    awan: 'میمون',
    metal: 'سیسہ',
    color: 'تاریک سرمئی',
    incense: 'صبر و حلتیک',
    bodyPart: 'تلی اور صفراء'
  },
  'ت': {
    letter: 'ت',
    name: 'تاء',
    abjadKabir: 400,
    abjadSaghir: 4,
    abjadWasit: 40,
    abjadAkbar: 400,
    element: 'air',
    elementUrdu: 'بادی (گرم و تر)',
    nature: 'گرم و تر (مرتبہ ششم)',
    planet: 'Sun',
    planetUrdu: 'شمس (سورج)',
    lunarMansion: {
      number: 22,
      name: 'سعد الذابح (Sa\'d al-Dhabih)',
      degree: 'دلو ۱۲°۵۱\' تا ۲۵°۴۲\'',
      spiritualEffect: 'شفائے مریض، نجات از قید اور دافعِ آفات'
    },
    nazeerah: 'ح',
    nazeerahAbjad: 8,
    oppositeElement: 'خاکی (سرد و خشک)',
    isNourani: false,
    isSowamat: false,
    pronunciationType: 'ملبوبی',
    muwakkil: 'روقیائیل ؑ',
    awan: 'المذہب',
    metal: 'سونا',
    color: 'سنہری شوخ',
    incense: 'عود و صندل سرخ',
    bodyPart: 'ہڈیاں اور ڈھانچہ'
  },
  'ث': {
    letter: 'ث',
    name: 'ثاء',
    abjadKabir: 500,
    abjadSaghir: 5,
    abjadWasit: 50,
    abjadAkbar: 500,
    element: 'water',
    elementUrdu: 'آبی (سرد و تر)',
    nature: 'سرد و تر (مرتبہ ششم)',
    planet: 'Moon',
    planetUrdu: 'قمر (چاند)',
    lunarMansion: {
      number: 23,
      name: 'سعد بلع (Sa\'d Bula)',
      degree: 'حوت ۰° تا ۱۲°۵۱\'',
      spiritualEffect: 'درمان، علاجِ سحر، دفعِ نظرِ بد اور تسکین'
    },
    nazeerah: 'ط',
    nazeerahAbjad: 9,
    oppositeElement: 'آتشی (گرم و خشک)',
    isNourani: false,
    isSowamat: false,
    pronunciationType: 'ملبوبی',
    muwakkil: 'جبرائیل ؑ',
    awan: 'مرّة',
    metal: 'چاندی',
    color: 'نقرئی و شفاف',
    incense: 'کافور و گلاب',
    bodyPart: 'جلد، چمڑا اور بال'
  },
  'خ': {
    letter: 'خ',
    name: 'خاء',
    abjadKabir: 600,
    abjadSaghir: 6,
    abjadWasit: 60,
    abjadAkbar: 600,
    element: 'earth',
    elementUrdu: 'خاکی (سرد و خشک)',
    nature: 'سرد و خشک (مرتبہ ششم)',
    planet: 'Mars',
    planetUrdu: 'مریخ (بہام)',
    lunarMansion: {
      number: 24,
      name: 'سعد السعود (Sa\'d al-Su\'ud)',
      degree: 'حوت ۱۲°۵۱\' تا ۲۵°۴۲\'',
      spiritualEffect: 'سعدِ اکبر، نکاح، دوستی، زراعت اور نفعِ کثیر'
    },
    nazeerah: 'ی',
    nazeerahAbjad: 10,
    oppositeElement: 'بادی (گرم و تر)',
    isNourani: false,
    isSowamat: false,
    pronunciationType: 'ملبوبی',
    muwakkil: 'سمسمائیل ؑ',
    awan: 'الاحمر',
    metal: 'فولاد',
    color: 'خونی لال',
    incense: 'حرمل و رائی',
    bodyPart: 'رگیں اور شریانیں'
  },
  'ذ': {
    letter: 'ذ',
    name: 'ذال',
    abjadKabir: 700,
    abjadSaghir: 7,
    abjadWasit: 70,
    abjadAkbar: 700,
    element: 'fire',
    elementUrdu: 'آتشی (گرم و خشک)',
    nature: 'گرم و خشک (مرتبہ ہفتم)',
    planet: 'Mercury',
    planetUrdu: 'عطارد (تیر)',
    lunarMansion: {
      number: 25,
      name: 'سعد الأخبية (Sa\'d al-Akhbiyah)',
      degree: 'حمل ۰° تا ۱۲°۵۱\' (دور ثانی)',
      spiritualEffect: 'کشفِ اسرار، گنجِ مخفی اور امراضِ خبیثہ کا علاج'
    },
    nazeerah: 'ک',
    nazeerahAbjad: 20,
    oppositeElement: 'آبی (سرد و تر)',
    isNourani: false,
    isSowamat: false,
    pronunciationType: 'ملفوظی',
    muwakkil: 'میکائیل ؑ',
    awan: 'برقان',
    metal: 'پارہ و برونز',
    color: 'سبز خاکی',
    incense: 'جاوتری و لبان',
    bodyPart: 'معدہ اور آنتیں'
  },
  'ض': {
    letter: 'ض',
    name: 'ضاد',
    abjadKabir: 800,
    abjadSaghir: 8,
    abjadWasit: 80,
    abjadAkbar: 800,
    element: 'air',
    elementUrdu: 'بادی (گرم و تر)',
    nature: 'گرم و تر (مرتبہ ہفتم)',
    planet: 'Jupiter',
    planetUrdu: 'مشتری (برجیس)',
    lunarMansion: {
      number: 26,
      name: 'فرغ المقدم (Fargh al-Muqaddam)',
      degree: 'ثور ۰° تا ۱۲°۵۱\' (دور ثانی)',
      spiritualEffect: 'محبت، الفت، صحت یابی اور امراء کی تسخیر'
    },
    nazeerah: 'ل',
    nazeerahAbjad: 30,
    oppositeElement: 'خاکی (سرد و خشک)',
    isNourani: false,
    isSowamat: false,
    pronunciationType: 'ملفوظی',
    muwakkil: 'صرفیائیل ؑ',
    awan: 'شمهورش',
    metal: 'پیتل',
    color: 'نیلا لاجوردی',
    incense: 'عنبر و مشک',
    bodyPart: 'دماغ اور اعصابی نظام'
  },
  'ظ': {
    letter: 'ظ',
    name: 'ظاء',
    abjadKabir: 900,
    abjadSaghir: 9,
    abjadWasit: 90,
    abjadAkbar: 900,
    element: 'water',
    elementUrdu: 'آبی (سرد و تر)',
    nature: 'سرد و تر (مرتبہ ہفتم)',
    planet: 'Venus',
    planetUrdu: 'زہرہ (ناہید)',
    lunarMansion: {
      number: 27,
      name: 'فرغ المؤخر (Fargh al-Mu\'akhkhar)',
      degree: 'جوزا ۰° تا ۱۲°۵۱\' (دور ثانی)',
      spiritualEffect: 'دولت، تجارت، مچھلی کا شکار اور صلح و امن'
    },
    nazeerah: 'م',
    nazeerahAbjad: 40,
    oppositeElement: 'آتشی (گرم و خشک)',
    isNourani: false,
    isSowamat: false,
    pronunciationType: 'ملبوبی',
    muwakkil: 'عنیائیل ؑ',
    awan: 'زوبعة',
    metal: 'تانبا',
    color: 'چمکیلا گلابی',
    incense: 'صندل و چنبیلی',
    bodyPart: 'اعصاب اور حسِ لمس'
  },
  'غ': {
    letter: 'غ',
    name: 'غین',
    abjadKabir: 1000,
    abjadSaghir: 1,
    abjadWasit: 100,
    abjadAkbar: 1000,
    element: 'earth',
    elementUrdu: 'خاکی (سرد و خشک)',
    nature: 'سرد و خشک (مرتبہ ہفتم)',
    planet: 'Saturn',
    planetUrdu: 'زحل (کیوان)',
    lunarMansion: {
      number: 28,
      name: 'الرشاء / بطن الحوت (Al-Risha)',
      degree: 'سرطان ۰° تا ۱۲°۵۱\' (دور ثانی)',
      spiritualEffect: 'تمام کاموں کی تکمیل، رزقِ وسیع، حفاظتِ سفر'
    },
    nazeerah: 'ن',
    nazeerahAbjad: 50,
    oppositeElement: 'بادی (گرم و تر)',
    isNourani: false,
    isSowamat: false,
    pronunciationType: 'ملفوظی',
    muwakkil: 'کسفیائیل ؑ',
    awan: 'میمون',
    metal: 'سیسہ',
    color: 'سیاہ و سرمئی',
    incense: 'صبر و حلتیک',
    bodyPart: 'خون اور شریانی دورہ'
  }
};

export const KASH_AL_BARNY_SYMBOL_PRESETS: JafrSymbolPreset[] = [
  {
    id: 'miftah-noorani-14',
    nameUrdu: 'حروفِ نورانیہ کے چودہ اسرار (نص حکیم قاطع له سر)',
    sequence: 'ا ح ر س ص ط ع ق ک ل م ن ہ ی',
    bookSource: 'مفتاح الجفر (کاش البرنی) - باب الحروف و المقطعات',
    category: 'miftah_jafr',
    categoryUrdu: 'مفتاح الجفر (اسرارِ حروف)',
    descriptionUrdu: 'قرآن کریم کے وہ ۱۴ حروف جن سے سورتوں کے آغاز میں مقطعات بنے ہیں۔ کاش البرنی فرماتے ہیں کہ یہ حروفِ نورانی تمام نورانی عملیات و شفاء اور تسخیرِ علوی کی کلید ہیں۔',
    esotericSecret: 'مجموعہ اعداد ابجد کبir = 693۔ ان کے ذریعے استخراج شدہ موکل علوی تمام سفلی اثرات کو جلا کر راکھ کر دیتا ہے۔',
    recommendedUse: 'اعمالِ شفاء، فراخی رزق، کشف القلوب، اور ہرن کی جھلی پر زعفران سے نقش لکھنا۔'
  },
  {
    id: 'qawaneen-zulmani-14',
    nameUrdu: 'حروفِ ظلمانیہ و دافعِ شرور و اعداء',
    sequence: 'ب ت ث ج خ د ذ ز ش ض ظ غ ف و',
    bookSource: 'قوانینِ طلسم (کاش البرنی) - باب العناصر و قفل الشرور',
    category: 'qawaneen_tilism',
    categoryUrdu: 'قوانینِ طلسم (قفل و ہیبت)',
    descriptionUrdu: 'وہ ۱۴ حروف جن کے اندر جلالی اور خاکی و آتشی غلبہ پایا جاتا ہے۔ کاش البرنی کے مطابق جب دشمنوں کی زبان بندی یا سرکش جنات کے حصار کا ارادہ ہو تو ان کا تصریف کیا جاتا ہے۔',
    esotericSecret: 'مجموعہ ابجد کبیر = 5302۔ ان سے استخراج شدہ عون سفلی کا نام حصار کے بیرونی کونوں پر لکھا جاتا ہے۔',
    recommendedUse: 'زبان بندی، حصارِ فولادی، دفعِ اثراتِ جادو اور مریخ کی ساعت میں عمل۔'
  },
  {
    id: 'aflatoon-ayqagh-fire',
    nameUrdu: 'قوانینِ افلاطون: قطبِ عناصرِ آتشی (ایقغ)',
    sequence: 'ا ہ ط م ف ش ذ',
    bookSource: 'قوانینِ افلاطون (کاش البرنی) - قانون التوافق الناری',
    category: 'qawaneen_aflatoon',
    categoryUrdu: 'قوانینِ افلاطون (عناصر)',
    descriptionUrdu: 'افلاطون کا وہ قطعی اصول جس کے مطابق حرارتِ غریزیہ اور قلب میں جلن و بے قراری پیدا کرنے کے لیے حروفِ آتشی کو درجہ بہ درجہ بیدار کیا جاتا ہے۔',
    esotericSecret: 'اعداد: ۱، ۵، ۹، ۴۰، ۸۰، ۳۰۰، ۷۰۰ (کل: ۱۱۳۵)۔ شمس و مریخ کے باہمی شرف پر یہ سلسلہ محبت میں بے پناہ تڑپ پیدا کرتا ہے۔',
    recommendedUse: 'جلبِ محبت، برطرفی سستی و کاہلی، حصولِ شجاعت اور ساعتِ شمس میں بخورِ عود جلانا۔'
  },
  {
    id: 'aflatoon-badi-air',
    nameUrdu: 'قوانینِ افلاطون: حروفِ ہوائیہ و الفتِ قلبی',
    sequence: 'ب و ی ن ص ت ض',
    bookSource: 'قوانینِ افلاطون (کاش البرنی) - قانون الجذب الروحی',
    category: 'qawaneen_aflatoon',
    categoryUrdu: 'قوانینِ افلاطون (عناصر)',
    descriptionUrdu: 'ہوائی حروف جو لطیف ارواح کو حرکت دیتے ہیں اور مطلوب کے دل و دماغ میں طالب کا خیال کثرت سے لاتے ہیں۔',
    esotericSecret: 'اعداد: ۲، ۶، ۱۰، ۵۰، ۹۰، ۴۰۰، ۸۰۰ (کل: ۱۳۵۸)۔ زہرہ اور مشتری کی ساعت میں سریع التاثیر ہے۔',
    recommendedUse: 'تسخیرِ قلوب، پیغام رسانی باطن، صلح میان زوجین، اور ساعتِ زہرہ میں بخورِ لبان جلانا۔'
  },
  {
    id: 'rumooz-badooh-talisman',
    nameUrdu: 'رموز التکسیر: طلسمِ بدوح السریع (۲-۴-۶-۸)',
    sequence: 'ب د و ح',
    bookSource: 'رموز الجفر و علم التکسیر (کاش البرنی) - طلسماتِ ارباب العرش',
    category: 'rumooz_takseer',
    categoryUrdu: 'رموز التکسیر (الواح)',
    descriptionUrdu: 'طلسمِ بدوح وہ مشہور و مجرب طلسم ہے جس کے اعداد ۲، ۴، ۶، ۸ ہیں (کل عدد: ۲۰)۔ یہ طلسم خطوط کی ترسیل، گمشدہ کی واپسی اور کاموں کی تیز رفتار تکمیل کے لیے اکسیر ہے۔',
    esotericSecret: 'موکل علوی: بدوحیائیلؑ۔ جب تکسیر کے ساتھ لکھا جائے تو ۴ سطور میں زمام پا لیتا ہے۔',
    recommendedUse: 'خط، پیکٹ یا دکان کی چوکھٹ پر لکھنا، مسافرت میں حفاظت اور سرعتِ کار۔'
  },
  {
    id: 'miftah-ajhaz-planetary',
    nameUrdu: 'مفتاح الجفر: طلسمِ اجهزط الکوکبی و المفتاح',
    sequence: 'ا ج ہ ز ط',
    bookSource: 'مفتاح الجفر (کاش البرنی) - باب المفاتیح و الاوتاد',
    category: 'miftah_jafr',
    categoryUrdu: 'مفتاح الجفر (اسرارِ حروف)',
    descriptionUrdu: 'طاق حروف کا طلسماتی مجموعہ (۱، ۳، ۵، ۷، ۹ = کل عدد ۲۵)۔ کاش البرنی کے نزدیک یہ وہ طلسم ہے جو تمام مفاتیحِ جفریہ کا تالا کھولتا ہے۔',
    esotericSecret: 'مربع ۲۵ کی اساس۔ اس کے مؤکلین علوی و سفلی باہم مل کر عجائب ظاہر کرتے ہیں۔',
    recommendedUse: 'قفل کشائی، گتھیوں کا سلجھاؤ، استخارہ و کشف الغطاء۔'
  },
  {
    id: 'biruni-28-abjad-circle',
    nameUrdu: 'کتاب التفهیم للبیرونی: تسلسلِ ابجدِ کبیر (۲۸ حروف فلکیہ)',
    sequence: 'ا ب ج د ہ و ز ح ط ی ک ل م ن س ع ف ص ق ر ش ت ث خ ذ ض ظ غ',
    bookSource: 'کتاب التفهیم لأوائل صناعة التنجيم (ابو ریحان البیرونی)',
    category: 'biruni_astronomy',
    categoryUrdu: 'علم الفلک و البیرونی',
    descriptionUrdu: 'ابو ریحان البیرونی کا مکمل فلکی و عددی نظام جس میں ۲۸ حروف کو ۲۸ منازلِ قمر اور ۱۲ بروج پر ریاضیاتی اصول کے تحت منطبق کیا گیا ہے۔',
    esotericSecret: 'مجموعہ ابجد کبیر = ۵۹۹۵۔ یہ دائرہ کائنات کی تمام حرکات و سکنات کا محیط ہے۔',
    recommendedUse: 'رصدِ کواکب، تقویمِ فلکیہ، استخراجِ طالع اور الواحِ جامعہ کی تیاری۔'
  },
  {
    id: 'qawaneen-sowamat-shield',
    nameUrdu: 'قوانینِ طلسم: حروفِ صوامت (بے نقط حصارِ فولادی)',
    sequence: 'ا ح د ر س ص ط ع ک ل م ہ و',
    bookSource: 'قوانینِ طلسم (کاش البرنی) - باب الحصون المنیعة',
    category: 'qawaneen_tilism',
    categoryUrdu: 'قوانینِ طلسم (قفل و ہیبت)',
    descriptionUrdu: 'بے نقط حروف جن پر شیاطین اور جنات کا کوئی بس نہیں چلتا۔ کاش البرنی فرماتے ہیں کہ ان حروف سے تیار کردہ لوح کو کوئی ساحر توڑ نہیں سکتا۔',
    esotericSecret: 'حروف کی تعداد: ۱۳۔ کل عدد: ۲۹۰۔ یہ سحر اور شریر ارواح کے لیے ناقابلِ عبور دیوار بن جاتے ہیں۔',
    recommendedUse: 'حصارِ خود و مکان، علاجِ مریضِ آسیب زدہ، اور تانبے کی تختی پر کندہ کر کے گلے میں ڈالنا۔'
  },
  {
    id: 'salimani-seven-shawaaz',
    nameUrdu: 'کاش البرنی: طلسمِ سبعہ شواذ (خاتمِ سلیمانی)',
    sequence: 'ف ج ش ث ظ خ ز',
    bookSource: 'مفتاح الجفر و قوانینِ طلسم (کاش البرنی) - باب الخواتم السبعة',
    category: 'salimani_tilism',
    categoryUrdu: 'طلسماتِ سلیمانی',
    descriptionUrdu: 'سات حروفِ شواذ جو سورہ فاتحہ میں نہیں آئے (ف، ج، ش، ث، ظ، خ، ز)۔ یہ ساتوں حروف سات کواکب اور سات ملوکِ جن کے اسم اعظم کی چابی ہیں۔',
    esotericSecret: 'مجموعہ اعداد = ۲۳۱۸۔ سات دنوں کے سات موکلین کی تسخیر کا سربستہ راز ہے۔',
    recommendedUse: 'ابطالِ ہر قسم کے طلسمات، تسخیرِ جنات، اور جمعرات یا جمعہ کی شب تحریر کرنا۔'
  },
  {
    id: 'miftah-kashlhoon-majestic',
    nameUrdu: 'مفتاح الجفر: طلسمِ کعسلہون الغالب (ہیبت و نصرت)',
    sequence: 'ک ع س ل ہ و ن',
    bookSource: 'مفتاح الجفر (کاش البرنی) - باب اسماء الطلاسم الجلیلة',
    category: 'miftah_jafr',
    categoryUrdu: 'مفتاح الجفر (اسرارِ حروف)',
    descriptionUrdu: 'کاش البرنی کی کتاب کا وہ پر ہیبت طلسم جو عدالت، حاکم کے روبرو اور دشمنوں کے سامنے غلبہ و فتح پانے کے لیے رقم کیا جاتا ہے۔',
    esotericSecret: 'مجموعہ اعداد = ۲۴۱۔ موکل: کعسلیائیلؑ۔ اس کا ورد زبان کو قاطع اور چہرے کو پر رعب بناتا ہے۔',
    recommendedUse: 'عدالتی کامیابی، انٹرویو و مناظرہ میں فتح، چاندی کی انگوٹھی کے نگینے پر کندہ کرنا۔'
  }
];

export const ZODIAC_SIGNS_URDU = [
  'برج حمل (Aries - آتشی)',
  'برج ثور (Taurus - خاکی)',
  'برج جوزا (Gemini - بادی)',
  'برج سرطان (Cancer - آبی)',
  'برج اسد (Leo - آتشی)',
  'برج سنبلہ (Virgo - خاکی)',
  'برج میزان (Libra - بادی)',
  'برج عقرب (Scorpio - آبی)',
  'برج قوس (Sagittarius - آتشی)',
  'برج جدی (Capricorn - خاکی)',
  'برج دلو (Aquarius - بادی)',
  'برج حوت (Pisces - آبی)',
];
