export interface IndexedOperation {
  id: string;
  title: string;
  urduTitle: string;
  purposeCategory: 
    | 'dafa_dushman_halakat'
    | 'dafeen_khazain'
    | 'mahabbat_sulh'
    | 'zaban_bandi_adalat'
    | 'taskheer_khalaiq'
    | 'taskheer_jinn_arwah'
    | 'shifa_amraz'
    | 'ibtal_sihr_asib'
    | 'rizq_tijarat'
    | 'kashf_istikhara'
    | 'hisar_hifazat';
  purposeCategoryUrdu: string;
  targetStudio: string;
  targetStudioNameUrdu: string;
  sourceBook: string;
  author: string;
  severity: 'safe' | 'caution' | 'warning' | 'critical_qahr';
  severityUrdu: string;
  speed: 'one_night' | 'three_days' | 'seven_days' | 'instant';
  speedUrdu: string;
  requiredSaat: string;
  suitableDay: string;
  element: 'fire' | 'air' | 'water' | 'earth';
  elementUrdu: string;
  incense: string;
  inkAndPaper: string;
  direction: string;
  defaultAdad: number;
  defaultText: string;
  summary: string;
  preconditions: string[];
  steps: string[];
  azimatOrFormula: string;
  protectionMeasures: string[];
  warningsAndReboundNotice?: string;
  badge?: string;
}

export interface PurposeCategoryMeta {
  id: string;
  titleUrdu: string;
  subtitleUrdu: string;
  iconName: string;
  colorClass: string;
  bgColorClass: string;
  borderColorClass: string;
  count?: number;
}

export const PURPOSE_CATEGORIES: PurposeCategoryMeta[] = [
  {
    id: 'all',
    titleUrdu: 'تمام عملیات و مقاصد (الکل)',
    subtitleUrdu: 'کتبِ قدیمہ کے تمام مجرب اعمال کا مکمل اشاریہ',
    iconName: 'Layers',
    colorClass: 'text-[#5d4037]',
    bgColorClass: 'bg-[#faedcd]',
    borderColorClass: 'border-[#d4a373]',
  },
  {
    id: 'dafa_dushman_halakat',
    titleUrdu: 'دفعِ دشمن، قہرِ اعداء و ہلاکتِ ظالم (شبِ واحد)',
    subtitleUrdu: 'ایک رات میں دشمن کا شر زائل کرنے اور ظالم کو کیفرِ کردار تک پہنچانے کے جگری طلسمات',
    iconName: 'Flame',
    colorClass: 'text-[#9d0208]',
    bgColorClass: 'bg-[#ffe5d9]',
    borderColorClass: 'border-[#d00000]',
  },
  {
    id: 'dafeen_khazain',
    titleUrdu: 'استخراجِ دفائن، کنوز و جذبِ خزائن از زمین',
    subtitleUrdu: 'زمین سے پوشیدہ خزانہ کھینچنے، اوپر لانے اور موانع و طلسمات توڑنے کے جفری اعمال و نقوش',
    iconName: 'Gem',
    colorClass: 'text-[#b5838d]',
    bgColorClass: 'bg-[#f8edeb]',
    borderColorClass: 'border-[#e07a5f]',
  },
  {
    id: 'mahabbat_sulh',
    titleUrdu: 'محبت، الفت، وصل، جلب و صلحِ زوجین',
    subtitleUrdu: 'قلوب میں غیر متزلزل پیار، ازدواجی ناچاقی کا خاتمہ اور تسخیرِ حلال',
    iconName: 'Heart',
    colorClass: 'text-[#e63946]',
    bgColorClass: 'bg-[#fce4ec]',
    borderColorClass: 'border-[#f48fb1]',
  },
  {
    id: 'zaban_bandi_adalat',
    titleUrdu: 'عقد اللسان، زبان بندی و فتح در عدالت',
    subtitleUrdu: 'حاسدوں کی زبانیں مقفل کرنا، کورٹ کچہری میں کامیابی اور جھوٹے مقدمات کا خاتمہ',
    iconName: 'Lock',
    colorClass: 'text-[#bc6c25]',
    bgColorClass: 'bg-[#fefae0]',
    borderColorClass: 'border-[#dda15e]',
  },
  {
    id: 'taskheer_khalaiq',
    titleUrdu: 'تسخیر خلائق، وجاہت و تسخیرِ حکام',
    subtitleUrdu: 'عوام میں رعب و دبدبہ، عزت و وقار، افسران کی نظر میں مقبولیت و منصب',
    iconName: 'Users',
    colorClass: 'text-[#1d3557]',
    bgColorClass: 'bg-[#e0f2fe]',
    borderColorClass: 'border-[#7dd3fc]',
  },
  {
    id: 'taskheer_jinn_arwah',
    titleUrdu: 'تسخیرِ جنات و ارواح، چلے و ریاضات',
    subtitleUrdu: 'روحانی قوتوں سے رابطہ، اعوان کا استخراج اور مندل کی شرائط',
    iconName: 'Sparkles',
    colorClass: 'text-[#6b21a8]',
    bgColorClass: 'bg-[#f3e8ff]',
    borderColorClass: 'border-[#d8b4fe]',
  },
  {
    id: 'shifa_amraz',
    titleUrdu: 'شفا، تندرستی، امراضِ خبیثہ و جڑی بوٹیاں',
    subtitleUrdu: 'جسمانی و روحانی بیماریوں کا علاج بمطابق شفاء الاسقام و طبِ ابن سینا',
    iconName: 'HeartPulse',
    colorClass: 'text-[#2a9d8f]',
    bgColorClass: 'bg-[#e6f4ea]',
    borderColorClass: 'border-[#a7d7c5]',
  },
  {
    id: 'ibtal_sihr_asib',
    titleUrdu: 'ابطالِ سحر، دفعِ نظرِ بد و کالے جادو کی کاٹ',
    subtitleUrdu: 'سفلی اثرات، باندھ، نظرِ بد اور سحرِ اسود کو جڑ سے اکھاڑ پھینکنے کے طلسمات',
    iconName: 'ShieldAlert',
    colorClass: 'text-[#d90429]',
    bgColorClass: 'bg-[#fee2e2]',
    borderColorClass: 'border-[#fca5a5]',
  },
  {
    id: 'rizq_tijarat',
    titleUrdu: 'وسعتِ رزق، دولت، برکت و کشائشِ تجارت',
    subtitleUrdu: 'مال و زر میں برکت، گاہکوں کی کثرت، اور بندشِ روزگار کا فوری خاتمہ',
    iconName: 'Coins',
    colorClass: 'text-[#b08968]',
    bgColorClass: 'bg-[#fdf0d5]',
    borderColorClass: 'border-[#ddb892]',
  },
  {
    id: 'kashf_istikhara',
    titleUrdu: 'کشف، خواب، استخارہ و غیبی اسرار',
    subtitleUrdu: 'خواب میں سچی رہنمائی، باطنی بصیرت، اور نادیدہ معاملات کا سراغ لگانا',
    iconName: 'Eye',
    colorClass: 'text-[#457b9d]',
    bgColorClass: 'bg-[#f1faee]',
    borderColorClass: 'border-[#a8dadc]',
  },
  {
    id: 'hisar_hifazat',
    titleUrdu: 'حصارِ اعظم، فولادی قلعہ و حفاظتِ جان و مال',
    subtitleUrdu: 'ہر قسم کے باطنی حملے، رجعت اور جادو سے بچاؤ کا ناقابلِ تسخیر حفاظتی حصار',
    iconName: 'ShieldCheck',
    colorClass: 'text-[#2b9348]',
    bgColorClass: 'bg-[#e8f5e9]',
    borderColorClass: 'border-[#81c784]',
  },
];

export const JAFR_INDEXED_OPERATIONS: IndexedOperation[] = [
  // ==========================================
  // SECTION 1: DAFA-E-DUSHMAN & HALAKAT-E-ZALIM (SHAB-E-WAHID)
  // ==========================================
  {
    id: 'op-dafa-dushman-tamtam-1night',
    title: 'Tamtam Hindi 1-Night Tyrant Overthrow',
    urduTitle: 'طلسمِ شطیثا و قہرِ عزرائیل فی لیلۃ واحدۃ (طمطم ہندی)',
    purposeCategory: 'dafa_dushman_halakat',
    purposeCategoryUrdu: 'دفعِ دشمن و ہلاکتِ ظالم (شبِ واحد)',
    targetStudio: 'tamtam-hindi',
    targetStudioNameUrdu: 'طلسماتِ طمطم ہندی و نوامیسِ کبار',
    sourceBook: 'طلسماتِ طمطم ہندی (الشیخ طمطم الہندی)',
    author: 'الشیخ طمطم الہندی',
    severity: 'critical_qahr',
    severityUrdu: 'سخت ترین جلال و قہر (خطرناک)',
    speed: 'one_night',
    speedUrdu: 'ایک رات میں (فی لیلۃ واحدۃ)',
    requiredSaat: 'ساعت مریخ (منگل کی شب نصف شب یا زوال)',
    suitableDay: 'منگل / شبِ چہار شنبہ',
    element: 'fire',
    elementUrdu: 'آتشی (ناری)',
    incense: 'حلتیک (ہینگ)، گوگرد (گندھک)، رائی، پوستِ پیاز',
    inkAndPaper: 'سیاہ سیاہی مع سرکہ بر نیلے کپڑے یا حنظل (کوڑ تمہ)',
    direction: 'جنوب یا مخالف کے گھر کی سمت',
    defaultAdad: 940,
    defaultText: 'یا قہار یا منتقم یا مذل خذ ظالم',
    summary: 'طمطم ہندی کا وہ لرزہ خیز طلسم جو صرف ایک رات میں ظالم کے تکبر، ستم اور شر کو اس کے اپنے سر پر الٹ دیتا ہے۔',
    badge: 'ایک رات کا جگری طلسم',
    preconditions: [
      'سخت ترین انتباہ: یہ عمل صرف اس صورت میں جائز ہے جب ظالم کا ظلم جان، مال، یا ناموس کے لیے یقینی خطرہ بن چکا ہو اور قانونی چارہ جوئی ناکام ہو چکی ہو۔',
      'ناحق کرنے کی صورت میں یہ قہر عامل اور اس کے اہل و عیال پر فوری طور پر الٹ جاتا ہے (رجعتِ کبیرہ)۔',
      'عمل سے قبل سیاہ بکرے کا صدقہ یا کالے ماش محتاجوں میں تقسیم کرنا اور فولادی حصار باندھنا قطعی فرض ہے۔',
    ],
    steps: [
      '1. نصف شب کے وقت تنہائی میں قبلہ کی بجائے جنوب رخ ہو کر بیٹھیں۔',
      '2. حنظل (کوڑ تمہ) کو چاقو سے چیر کر اس کے اندر مخالف کا نام مع والدہ اور حروفِ ظلمانیہ (ب، ت، ث، ج، خ، د، ذ، ز، ش، ض، ظ، غ، ف، و) معکوس لکھیں۔',
      '3. اسمائے قہریہ "یا قہار یا منتقم یا مذل" کے کل اعداد (۹۴۰) کا نقش مربع آتشی چال سے تحریر کریں۔',
      '4. گندھک اور ہینگ کی کثیف دھونی دیں اور عزیمتِ شطیثا ۷۳ مرتبہ پڑھ کر حنظل پر پھونکیں۔',
      '5. اس حنظل کو رات کی تاریکی میں کسی پرانی ویران قبر کے سرہانے یا آگ کے دہکتے ہوئے انگاروں میں دفن کر دیں۔ صبح تک ظالم پر شدید قہر و پریشانی مسلط ہو جائے گی۔',
    ],
    azimatOrFormula: 'عزمت علیکم یا معشر العفاریت الطماطمہ بحق شطیثا و بطشِ عزرائیل و ہیبۃِ قہار ان تقطعوا دابر فلاں بن فلاں الظالم فی لیلتی ہذہ',
    protectionMeasures: [
      'عمل سے قبل ۱۱ بار آیت الکرسی اور ۴ قل پڑھ کر اپنے گرد چھری سے دائرہ (مندل) کھینچیں۔',
      'گلے میں خاتمِ سلیمانی یا لوحِ صوامت پہن کر رکھیں۔',
    ],
    warningsAndReboundNotice: 'کسی بے گناہ یا معمولی رنجش پر اس عمل کا استعمال خود کشی کے مترادف ہے۔ کاش البرنی اور طمطم ہندی نے اس سے سخت ڈرایا ہے۔',
  },
  {
    id: 'op-halakat-zalim-ibnsina',
    title: 'Ibn Sina 5th Law: Dispersion of Tyrants',
    urduTitle: 'ناموسِ پنجم: ہلاکتِ مفسد و متفرق ساختنِ اعداء (ابن سینا)',
    purposeCategory: 'dafa_dushman_halakat',
    purposeCategoryUrdu: 'دفعِ دشمن و ہلاکتِ ظالم (شبِ واحد)',
    targetStudio: 'mujarrabat-ibn-sina',
    targetStudioNameUrdu: 'مجربات ابن سینا (علومِ خمسہ و طلسمات)',
    sourceBook: 'مجربات ابن سینا و طلسماتِ خمسہ',
    author: 'الشیخ الرئیس بو علی ابن سینا',
    severity: 'critical_qahr',
    severityUrdu: 'شدید جلال (قوانینِ ابن سینا)',
    speed: 'one_night',
    speedUrdu: 'ایک رات تا ۳ دن',
    requiredSaat: 'ساعت زحل (ہفتہ کی رات آخری پہر)',
    suitableDay: 'ہفتہ (زحل)',
    element: 'earth',
    elementUrdu: 'خاکی (سوداوی)',
    incense: 'صمغِ مر، رائی، حرمل، تخمِ سداب',
    inkAndPaper: 'شمعِ سیاہ موم بر اینٹِ کہنہ یا ورقِ رصاص (سیسہ)',
    direction: 'مغرب / تحت الثریٰ',
    defaultAdad: 1344,
    defaultText: 'متفرق باد جمیع اعداء و ظالمین',
    summary: 'ابن سینا کے علومِ خمسہ کا پانچواں ناموس جو دشمنوں کے جتھے کو منتشر اور ظالم کو بسترِ عجز پر ڈالنے کے لیے وضع کیا گیا ہے۔',
    badge: 'ابن سینا کا ناموسِ کبار',
    preconditions: [
      'پرہیز جلالی (حیوانی خوراک، دودھ، گوشت سے اجتناب)۔',
      'ظالم کی طرف سے مسلسل ایذارسانی اور سچائی کا قطعی ثبوت۔',
    ],
    steps: [
      '1. ہفتہ کی رات کے آخری پہر سیاہ رنگ کی شمع روشن کریں۔',
      '2. شمع کے گرد ۱۳ حروفِ صوامت بے نقط (ا، ح، د، ر، س، ص، ط، ع، ک، ل، م، و، ہ) کو الٹا کندہ کریں۔',
      '3. تکسیر صدر و مؤخر سے حاصل شدہ عون سفلی "طوش" کا نام ۱۰۰ بار ضرب لگا کر پڑھیں۔',
      '4. سیسے (Lead Plate) پر نقش مخمس خاکی چال سے مرتب کر کے مخالف کے مکان کے قریب یا قبرستان کے راستے میں دبائیں۔',
    ],
    azimatOrFormula: 'یا شدید البطش یا قاصم الجبابرۃ اقصم ظہر فلاں بن فلاں و شتت شملہ کما شتت قوم ثمود و عاد',
    protectionMeasures: [
      'سورہ یٰس کی ۷ مبینوں پر الٹی سوئیاں لگا کر اپنے سامنے رکھیں اور اپنا حصار مضبوط کریں۔',
    ],
    warningsAndReboundNotice: 'ابن سینا نے کتاب کے حاشیے میں لکھا ہے کہ جو شخص اس ناموس کو ناحق آزمائے گا اس کا اپنا گھر ویران ہو جائے گا۔',
  },
  {
    id: 'op-dafa-zalim-kashalbarny',
    title: 'Kash Al-Barny Qahr-e-Aada Formula',
    urduTitle: 'طلسمِ کعسلہون الغالب و قہرِ خصم فی لیلۃ (کاش البرنی)',
    purposeCategory: 'dafa_dushman_halakat',
    purposeCategoryUrdu: 'دفعِ دشمن و ہلاکتِ ظالم (شبِ واحد)',
    targetStudio: 'aamal',
    targetStudioNameUrdu: 'دستور العمل و عملیات کاش البرنی',
    sourceBook: 'قوانینِ طلسم و رموز الجفر',
    author: 'کاش البرنی',
    severity: 'warning',
    severityUrdu: 'جلالی و قہریہ',
    speed: 'one_night',
    speedUrdu: 'شبِ واحد تا ۲۴ گھنٹے',
    requiredSaat: 'ساعت مریخ بوقتِ زوال یا شبِ منگل',
    suitableDay: 'منگل',
    element: 'fire',
    elementUrdu: 'آتشی',
    incense: 'گوگرد و رائی و لہسن کا چھلکا',
    inkAndPaper: 'سیاہ روشنائی بر زرد کاغذ یا تختی تانبہ',
    direction: 'مخالف کے شہر کی سمت',
    defaultAdad: 664,
    defaultText: 'کعسلہون الغالب قاہر الاعداء',
    summary: 'کاش البرنی کا مستند طلسم جو ظالم کے حملے کو اسی کی طرف پلٹ کر اسے بے دست و پا کر دیتا ہے۔',
    badge: 'کاش البرنی قہرِ اعداء',
    preconditions: [
      'عامل کا باوضو ہونا اور ۳ دن پہلے سے استغفار کی کثرت۔',
      'مخالف کی ماں کا نام معلوم نہ ہونے پر "حواء" فرض کیا جائے لیکن حساب درست ہو۔',
    ],
    steps: [
      '1. تکسیر صدر و مؤخر سے طلسماتی اسم برآمد کریں۔',
      '2. نقشِ مثلث آتشی معکوس تیار کریں جس کے ارد گرد آیت "فَقُطِعَ دَابِرُ الْقَوْمِ الَّذِينَ ظَلَمُوا..." لکھی ہو۔',
      '3. نقش کو دہکتے ہوئے کوئلوں پر رکھیں لیکن جلنے نہ دیں، صرف تپش پہنچائیں۔',
      '4. جوں جوں نقش تپے گا، ظالم پر رعب اور اضطراب طاری ہو گا۔',
    ],
    azimatOrFormula: 'اللہم یا قاہر یا قادر یا مقتدر یا منتقم خذ من ظلمنی و تعدی علی بحق کعسلہون الغالب',
    protectionMeasures: ['آیت الکرسی ۷ بار پڑھ کر اپنے دائیں بائیں حصار کھینچیں۔'],
  },
  {
    id: 'op-dafa-dushman-talismi-qadeem',
    title: 'Ancient Vedic Maran & Uchatan Avertment',
    urduTitle: 'طلسمِ حنظل و خاکِ قبرستانِ کہنہ برائے دفعِ ستمگر (طلسمِ قدیم)',
    purposeCategory: 'dafa_dushman_halakat',
    purposeCategoryUrdu: 'دفعِ دشمن و ہلاکتِ ظالم (شبِ واحد)',
    targetStudio: 'talismi-qadeem',
    targetStudioNameUrdu: 'طلسمِ قدیم (ویدک منترات و تسخیرِ بعید)',
    sourceBook: 'طلسمِ قدیم و شاسترِ باطن',
    author: 'حکماء ویدک و جفرِ قدیم',
    severity: 'critical_qahr',
    severityUrdu: 'شدید جلال (اوچاتن و دفع)',
    speed: 'one_night',
    speedUrdu: 'شبِ اماوس (ایک رات)',
    requiredSaat: 'ساعت زحل در شبِ تاریک',
    suitableDay: 'ہفتہ (رات)',
    element: 'earth',
    elementUrdu: 'خاکی و آتشی',
    incense: 'سرسوں، نیم کے پتے، رائی',
    inkAndPaper: 'سیاہ کاجل و تلسی کا رس بر بھوج پتر',
    direction: 'جنوب مغرب',
    defaultAdad: 432,
    defaultText: 'اوچاتن شمن دفع ستمگر',
    summary: 'قدیم شاستروں کا وہ قاطع عمل جو دشمن کے ناپاک ارادوں کو توڑ کر اسے اپنے دفاع پر مجبور کر دیتا ہے۔',
    badge: 'قدیم اوچاتن',
    preconditions: ['صرف دفعِ شر کے لیے، ذاتی حسد یا لالچ کے لیے کرنا خود ہلاکت ہے۔'],
    steps: [
      '1. شبِ اماوس میں پرانے قبرستان یا چوراہے کی مٹی لیں۔',
      '2. بھوج پتر پر منتر اور یینتر سیاہ کاجل سے تحریر کریں۔',
      '3. مٹی پر ۲۱ بار دم کر کے دشمن کے راستے میں پھینکیں۔',
    ],
    azimatOrFormula: 'اوم شمن شمن شترو ناشائے نوارن کروں کروں پھٹ سواہا',
    protectionMeasures: ['رکشا ریکھا (حفاظتی لکیر) سے باہر قدم نہ نکالیں۔'],
  },

  // ==========================================
  // SECTION 2: DAFEEN & KHAZAIN (PULLING TREASURES FROM GROUND)
  // ==========================================
  {
    id: 'op-dafeen-shaq-al-ard-buni',
    title: 'Buni Shaq al-Ard & Instant Treasure Surface Pull',
    urduTitle: 'طلسمِ شق الارض و کھینچنا دفینہ بر سطحِ خاک فی المرۃ الواحدۃ (شمس المعارف)',
    purposeCategory: 'dafeen_khazain',
    purposeCategoryUrdu: 'استخراجِ دفائن و جذبِ خزائن',
    targetStudio: 'naqsh',
    targetStudioNameUrdu: 'مولد النقوش و الواح',
    sourceBook: 'شمس المعارف الکبریٰ و لطائف العوارف',
    author: 'الشیخ احمد بن علی البونیؒ',
    severity: 'caution',
    severityUrdu: 'محتاط (ارصاد و موانع)',
    speed: 'instant',
    speedUrdu: 'ایک ہی نشست میں (فی المرۃ)',
    requiredSaat: 'ساعت مشتری در شرفِ مشتری یا نصف شبِ جمعرات',
    suitableDay: 'جمعرات / شبِ جمعہ',
    element: 'earth',
    elementUrdu: 'خاکی و ناری',
    incense: 'لوبانِ ذکر، سندروس، کافور، جاوا',
    inkAndPaper: 'زعفران و مشک بر پترہ تانبہ یا کورا مٹی کا برتن',
    direction: 'قبلہ رخ روبہ موضعِ دفینہ',
    defaultAdad: 1196,
    defaultText: 'وَأَلْقَتْ مَا فِيهَا وَتَخَلَّتْ یا باسط یا فتاح اخرج الکنز',
    summary: 'شمس المعارف الکبریٰ کا وہ مشہورِ زمانہ عمل جس میں سورہ انشقاق اور اسمائے اخراج کے ذریعے زمین میں چھپا ہوا خزانہ، زر یا دھاتیں اوپر کی طرف کھنچ کر سطح پر نمودار ہو جاتی ہیں۔',
    badge: 'خزانہ کھینچنے کا طلسمِ اعظم',
    preconditions: [
      'دفینہ کے مقام پر پہلے سے موجود طلسماتی ناگ، جنات یا ارصاد (حفاظتی پہرے داروں) کا حصار توڑنا اور باطنی حفاظت کرنا۔',
      'حلال نیت اور حاصل شدہ خزانے میں سے شرعی خمس (۲۰ فیصد صدقہ و خیرات) فقراء میں تقسیم کرنے کا عہد۔',
      'عمل کے دوران زمین پر کسی قسم کا خوف یا پیچھے مڑ کر دیکھنے سے سخت اجتناب۔',
    ],
    steps: [
      '1. مشتبہ یا معین مقامِ دفینہ پر چاروں کونوں پر ۴ فولادی میخیں ٹھونک کر ان کے گرد آیت الکرسی کا مندل قائم کریں۔',
      '2. کورا مٹی کا پیالہ یا تانبے کی تختی پر عدد ۱۱۹۶ کا نقش مربع ترابی چال سے زعفران و مشک سے تیار کریں۔',
      '3. نقش کے درمیان آیت: "وَأَلْقَتْ مَا فِيهَا وَتَخَلَّتْ وَأَذِنَتْ لِرَبِّهَا وَحُقَّتْ" اور چاروں اطراف اسماء "یا ظاہر یا باطن یا فتاح یا مخرج" لکھیں۔',
      '4. پیالے کو زمین پر الٹا رکھیں اور لوبان و سندروس کی دھونی دیتے ہوئے عزیمتِ شق الارض کو ۳۱۳ بار یا ایک ہی ضرب میں تلاوت کریں۔',
      '5. زمین کی گہرائی سے ارتعاش پیدا ہوگا اور مدفون شے یا برتن کھنچ کر اوپر کی طرف آ جائے گا۔',
    ],
    azimatOrFormula: 'بِسْمِ اللَّهِ الَّذِي شَقَّ الْأَرْضَ بِقُدْرَتِهِ، وَأَخْرَجَ أَثْقَالَهَا بِإِرَادَتِهِ، يَا مَعْشَرَ الْأَرْوَاحِ الْأَرْضِيَّةِ وَالْمُوَكِّلِينَ بِهَذَا الدَّفِينِ، أَخْرِجُوا مَا تَحْتَ أَقْدَامِكُمْ بِحَقِّ: وَأَلْقَتْ مَا فِيهَا وَتَخَلَّتْ، السَّاعَةَ السَّاعَةَ الْعَجَلَ الْعَجَلَ',
    protectionMeasures: [
      'عامل کے سینے پر لوحِ خاتم سلیمانی اور زبان پر "یا حفیظ یا سلام" کا ورد ہو۔',
      'مندل سے باہر قدم نہ نکالیں جب تک کہ عمل مکمل نہ ہو جائے۔',
    ],
    warningsAndReboundNotice: 'دفائن کے اوپر اکثر قدیم ارصاد و طلسمات قائم ہوتے ہیں، بغیر حصارِ فولادی کے یہ عمل کرنے سے جناتی آسیب کا حملہ ہو سکتا ہے۔',
  },
  {
    id: 'op-dafeen-tamtam-hindi-extract',
    title: 'Tamtam Hindi Subterranean Metal Attraction Talisman',
    urduTitle: 'طلسمِ جذبِ معادن و ارصادِ دفائن (طلسماتِ طمطم ہندی)',
    purposeCategory: 'dafeen_khazain',
    purposeCategoryUrdu: 'استخراجِ دفائن و جذبِ خزائن',
    targetStudio: 'tamtam-hindi',
    targetStudioNameUrdu: 'طلسماتِ طمطم ہندی و نوامیسِ کبار',
    sourceBook: 'طلسماتِ طمطم ہندی (الشیخ طمطم الہندی)',
    author: 'الشیخ طمطم الہندی',
    severity: 'warning',
    severityUrdu: 'جلالی و طلسماتی',
    speed: 'instant',
    speedUrdu: 'ایک نشست میں (یکبارگی)',
    requiredSaat: 'ساعت زحل بوقتِ قران یا نصف شبِ ہفتہ',
    suitableDay: 'ہفتہ (زحل)',
    element: 'earth',
    elementUrdu: 'خاکی و معدنی',
    incense: 'سندروس، مقل ازرق، مصطگی، صمغ عربی',
    inkAndPaper: 'سیاہیِ طلسم بر ورقِ رصاص (سیسہ) یا بھوج پتر',
    direction: 'مغرب و روبہ موضعِ مدفون',
    defaultAdad: 777,
    defaultText: 'جذب معادن و انشقاق تراب بحق طمطم',
    summary: 'طمطم ہندی کا وہ مخفی طلسم جو زمین کے اندر دبے ہوئے سونے، چاندی، اور تانبے کے برتنوں کو مقناطیسی کشش کی طرح اوپر کھینچ لاتا ہے اور زمینی ناگوں و طلسموں کو توڑتا ہے۔',
    badge: 'طمطم ہندی جذبِ معادن',
    preconditions: [
      'خلوت و تنہائی اور غیر عامل افراد کی موجودگی سے مکمل پرہیز۔',
      'سیسے کی تختی پر اعداد کی درستی۔',
    ],
    steps: [
      '1. سیسے کے پترے پر مثلث خاکی چال سے طلسمِ جذبِ معادن کندہ کریں۔',
      '2. پترے کو دفینے والی مٹی کے اوپر رکھ کر اس پر ۲۱ بار عزیمتِ صرصر پڑھیں۔',
      '3. مقل ازرق اور سندروس کی دھونی دیں۔ موکلینِ ارضی مجبور ہو کر دفینہ سطح پر پیش کر دیں گے۔',
    ],
    azimatOrFormula: 'عزمت علیکم یا خدام الرصاص و الجبال و المعادن بحق شطیش ۲ طمطیش ۲ اجلبوا ما فی باطن الارض الی ظاہرہا فی وقت و حین',
    protectionMeasures: ['حصارِ آہنی اور تلوار سے دائرہ قائم کرنا۔'],
    warningsAndReboundNotice: 'طلسماتی دفائن پر ارواحِ شریرہ ہو سکتی ہیں، توبہ و استغفار لازمی ہے۔',
  },
  {
    id: 'op-dafeen-kash-al-barny-miftah',
    title: 'Kash Al-Barny Treasure Unearthing & Earth Opening Formula',
    urduTitle: 'عملِ استخراجِ کنوز و کشفِ چشمہ و زرِ مدفون (کاش البرنی)',
    purposeCategory: 'dafeen_khazain',
    purposeCategoryUrdu: 'استخراجِ دفائن و جذبِ خزائن',
    targetStudio: 'jafr-symbolism',
    targetStudioNameUrdu: 'تحقیقِ رموز و اشاراتِ جفر (کاش البرنی)',
    sourceBook: 'مفتاح الجفر و قوانینِ طلسم (کاش البرنی)',
    author: 'کاش البرنی',
    severity: 'caution',
    severityUrdu: 'محتاط و حسابی',
    speed: 'one_night',
    speedUrdu: 'شبِ واحد تا ۲۴ گھنٹے',
    requiredSaat: 'ساعت شمس یا ساعت مشتری بوقتِ صبح صادق',
    suitableDay: 'اتوار یا جمعرات',
    element: 'earth',
    elementUrdu: 'ترابی و نوری',
    incense: 'عود قماری، لوبان، زعفران',
    inkAndPaper: 'زعفران و عرقِ گلاب بر کاغذِ زریں',
    direction: 'مشرق / قبلہ رخ',
    defaultAdad: 1380,
    defaultText: 'یا باسط یا فتاح یا وہاب یا مخرج الکنوز',
    summary: 'کاش البرنی کے مفتاح الجفر سے ماخوذ وہ ریاضیاتی و جفری عمل جس میں حروفِ مقطعات اور استخراجِ عونِ ارضی کے ذریعے دفینہ کی قطعی جگہ اور گہرائی کا پتہ لگا کر اسے اوپر کھینچا جاتا ہے۔',
    badge: 'مفتاح الجفر استخراجِ کنوز',
    preconditions: ['زمین کے مزاج کا توازن اور سائل کا باوضو و پاک لباس ہونا۔'],
    steps: [
      '1. مقامِ ارض کے نام اور سائل کے نام کے کل اعداد کا تکسیر کے ذریعے سطرِ امتزاج نکالیں۔',
      '2. استخراجِ موکل (مثلاً: کنزیائیل) اور عونِ سفلی برآمد کریں۔',
      '3. نقش مخمس خاکی تیار کر کے دفینے کے وسط میں دفن کریں، چند گھنٹوں میں علامت ظاہر ہوگی۔',
    ],
    azimatOrFormula: 'اللہم یا فالق الحب والنوی و مخرج الخبء فی السماوات والارض اخرج لنا کنوز ہذہ الارض و یسرہا لنا بلا مشقۃ ولا ضرر',
    protectionMeasures: ['آیت الکرسی اور ۴ قل کا حفاظتی قلعہ۔'],
  },
  {
    id: 'op-dafeen-ibn-sina-namoos',
    title: 'Ibn Sina Law of Subterranean Magnetism & Metal Elevation',
    urduTitle: 'ناموسِ ابن سینا برائے ظہورِ کنوز و کشفِ معادن (مجربات ابن سینا)',
    purposeCategory: 'dafeen_khazain',
    purposeCategoryUrdu: 'استخراجِ دفائن و جذبِ خزائن',
    targetStudio: 'mujarrabat-ibn-sina',
    targetStudioNameUrdu: 'مجربات ابن سینا (علومِ خمسہ و طلسمات)',
    sourceBook: 'مجربات ابن سینا و طلسماتِ خمسہ',
    author: 'الشیخ الرئیس بو علی ابن سینا',
    severity: 'caution',
    severityUrdu: 'حکیمانہ و طبعی',
    speed: 'instant',
    speedUrdu: 'فوری و حسابی',
    requiredSaat: 'ساعت عطارد بوقتِ شرف',
    suitableDay: 'بدھ',
    element: 'earth',
    elementUrdu: 'خاکی و معدنی',
    incense: 'جاوتری، دارچینی، صمغ عربی',
    inkAndPaper: 'سیاہی روغنِ سداب بر پترہ جست (زنک) یا تانبہ',
    direction: 'شمال',
    defaultAdad: 890,
    defaultText: 'قانون جذب معادن ارضیہ ابن سینا',
    summary: 'ابن سینا کے طبیعی و طلسماتی نوامیس کا وہ طریقہ جس میں ارضی عناصر کی مقناطیسی خاصیت کو بیدار کر کے چھپی ہوئی قیمتی دھاتوں اور خزانوں کو اوپر لایا جاتا ہے۔',
    badge: 'طبیعیاتِ ابن سینا',
    preconditions: ['زمین کی ساخت اور عنصرِ معدن کا علم ہونا۔'],
    steps: [
      '1. جست یا تانبے کی تختی پر طبیعی ہندسوں کا جدول تیار کریں۔',
      '2. اس تختی کو مقناطیسی قطب نما کی سمت میں زمین پر نصب کریں۔',
      '3. ناموسِ ثانی کے تحت مخصوص حرارت دے کر زیرِ زمین دھاتوں کو اپنی جانب کھینچیں۔',
    ],
    azimatOrFormula: 'بحق الطبائع الاربع و القوی الجاذبۃ فی الارض انبعث ایہا الجوہر المکتوم الی وجہ الثریٰ',
    protectionMeasures: ['فولادی حصار۔'],
  },

  // ==========================================
  // SECTION 3: MAHABBAT & SULH
  // ==========================================
  {
    id: 'op-mahabbat-sihr-al-ushaq',
    title: 'Sihr Al-Ushaq Universal Harmony & Love',
    urduTitle: 'طلسمِ جنۃ المشتاق و حرقِ قلوب برائے الفتِ زوجین (امام البونیؒ)',
    purposeCategory: 'mahabbat_sulh',
    purposeCategoryUrdu: 'محبت، الفت و صلحِ زوجین',
    targetStudio: 'sihr-al-ushaq',
    targetStudioNameUrdu: 'سحر العشاق و جنۃ المشتاق (امام البونیؒ)',
    sourceBook: 'سحر العشاق و جنۃ المشتاق فی جلب القلوب',
    author: 'الشیخ احمد بن علی البونیؒ',
    severity: 'safe',
    severityUrdu: 'خیر و جمالی (محبتِ شرعی)',
    speed: 'three_days',
    speedUrdu: '۳ دن تا ۷ دن',
    requiredSaat: 'ساعت زہرہ (جمعہ بوقت طلوع آفتاب)',
    suitableDay: 'جمعہ',
    element: 'water',
    elementUrdu: 'آبی و ہوائی',
    incense: 'مشک، عنبر، صندل سفید، گلاب',
    inkAndPaper: 'زعفران و عرق گلاب بر ورقِ آہو (ہرن کی جھلی) یا سفید کاغذ',
    direction: 'قبلہ رخ',
    defaultAdad: 110,
    defaultText: 'یا ودود یا حبیب الف بین فلاں و فلاں',
    summary: 'امام البونیؒ کا شہرہ آفاق نقش و طلسم جو ناراض میاں بیوی میں بیقرار کر دینے والی الفت اور محبت پیدا کرتا ہے۔',
    badge: 'امام البونیؒ کا مجرب ترین',
    preconditions: [
      'نیت خالصتاً نکاح، زوجین میں صلح یا جائز الفت کی ہو۔ ناجائز تعلق پر گناہِ کبیرہ ہے۔',
      'طالب اور مطلوب کے عناصر نکال کر موافقت کا لحاظ رکھا جائے۔',
    ],
    steps: [
      '1. جمعہ کے دن طلوع آفتاب کی پہلی ساعت میں غسل کر کے خوشبو لگائیں۔',
      '2. اسمائے الٰہی "یا ودود یا رؤوف یا رحیم" کے اعداد (۴۲۶) اور طالب و مطلوب کے ناموں کے اعداد جمع کریں۔',
      '3. نقش مثلث یا مخمس بادی چال سے زعفران سے تحریر کریں۔',
      '4. نقش کے چاروں کونوں پر ملائکہ اربعہ (جبرائیل، میکائیل، اسرافیل، عزرائیل) کے اسمائے مبارکہ لکھیں۔',
      '5. نقش کو صندل کی دھونی دے کر مطلوب کے عنصر کے مطابق استعمال کریں (اگر مطلوب آبی ہو تو پانی میں گھول کر پلائیں)۔',
    ],
    azimatOrFormula: 'یا ودود یا ذالعرش المجید یا مبدئ یا معید یا فعال لما یرید اسألک بنور وجہک الذی ملأ ارکان عرشک ان تجلب قلب فلاں الی فلاں',
    protectionMeasures: ['عمل سے قبل درود ابراہیمی ۱۱ بار پڑھیں۔'],
  },
  {
    id: 'op-mahabbat-aflatoon-harmony',
    title: 'Plato 4-Elements Cosmic Love Fusion',
    urduTitle: 'تکسیرِ افلاطونی و پیوندِ عناصرِ اربعہ برائے الفتِ دائمی',
    purposeCategory: 'mahabbat_sulh',
    purposeCategoryUrdu: 'محبت، الفت و صلحِ زوجین',
    targetStudio: 'aflatoon',
    targetStudioNameUrdu: 'تکسیرِ افلاطون (توازنِ عناصر)',
    sourceBook: 'قوانینِ افلاطون و تسخیرِ ارواح (کاش البرنی)',
    author: 'کاش البرنی بحوالہ حکیم افلاطون',
    severity: 'safe',
    severityUrdu: 'جمالی و سعد',
    speed: 'seven_days',
    speedUrdu: '۷ روز (پائیدار و دائمی)',
    requiredSaat: 'ساعت مشتری (جمعرات بوقتِ چاشت)',
    suitableDay: 'جمعرات',
    element: 'air',
    elementUrdu: 'بادی و مائی',
    incense: 'عودِ قماری، صندل سرخ، کافور',
    inkAndPaper: 'زعفران بر چاندی کے پترے یا روئی دار کاغذ',
    direction: 'مشرق',
    defaultAdad: 786,
    defaultText: 'محبت و یگانگت روح و جسم',
    summary: 'حکیم افلاطون کے قوانینِ اشراق کے تحت دو روحوں کے عناصر کا باہمی توازن اور غیر فانی الفت کا قیام۔',
    badge: 'افلاطونی کیمیا گری',
    preconditions: ['طالب اور مطلوب کے درمیانی متضاد عناصر کو عنصرِ ثالث سے معتدل کرنا۔'],
    steps: [
      '1. دونوں کے ناموں کے حروف کو الگ الگ کر کے آتشی، بادی، آبی اور خاکی خانوں میں تقسیم کریں۔',
      '2. تکسیر افلاطونی کے تحت سطرِ امتزاج تیار کریں۔',
      '3. زمام کے حروف کو چاندی کے پترے پر کندہ کر کے اپنے پاس رکھیں۔',
    ],
    azimatOrFormula: 'الف الف بین روحین کما الفت بین الماء و التراب و الشمس و القمر',
    protectionMeasures: ['ایت الکرسی کا حصار۔'],
  },

  // ==========================================
  // SECTION 3: ZABAN BANDI & ADALAT
  // ==========================================
  {
    id: 'op-zaban-bandi-kashalbarny',
    title: 'Language Sealing of Opponents & Court Victory',
    urduTitle: 'عمل عقد اللسان و گنگ ساختنِ حاسدان در محاکم (رموز الجفر)',
    purposeCategory: 'zaban_bandi_adalat',
    purposeCategoryUrdu: 'عقد اللسان و فتح در عدالت',
    targetStudio: 'aamal',
    targetStudioNameUrdu: 'دستور العمل و عملیات کاش البرنی',
    sourceBook: 'رموز الجفر و عقد اللسان (کاش البرنی)',
    author: 'کاش البرنی',
    severity: 'safe',
    severityUrdu: 'حفاظتی و صلح جویانہ',
    speed: 'instant',
    speedUrdu: 'بوقتِ ضرورت / فوری',
    requiredSaat: 'ساعت عطارد (بدھ) یا ساعت زحل',
    suitableDay: 'بدھ یا ہفتہ',
    element: 'earth',
    elementUrdu: 'خاکی',
    incense: 'جاوتری، لونگ، مصطگی رومی',
    inkAndPaper: 'سیاہ یا نیلے قلم سے سفید چکنے کاغذ پر',
    direction: 'مغرب',
    defaultAdad: 332,
    defaultText: 'عقد لسان اعداء و حاسدان',
    summary: 'ظالم حاکم، کینہ پرور رشتہ داروں اور عدالت میں مخالف گواہوں کی زبانیں گنگ کرنے کا تیر بہدف طریقہ۔',
    badge: 'عدالتی فتح و عقد لسان',
    preconditions: ['مخالف کی طرف سے جھوٹ اور تہمت کا ہونا۔ سچ دبانے کے لیے کرنا سخت ممنوع ہے۔'],
    steps: [
      '1. مخالف کا نام اور حروفِ صوامت (۱۳ حروف بے نقط) تحریر کریں۔',
      '2. اسم "یا صامت یا مانع یا قہار" کے اعداد نکال کر نقش مربع خاکی چال سے پر کریں۔',
      '3. نقش کے گرد "صُمٌّ بُكْمٌ عُمْيٌ فَهُمْ لَا يَرْجِعُونَ" لکھیں۔',
      '4. نقش کو کسی وزنی پتھر کے نیچے دبا دیں یا بوقتِ پیشی اپنی دائیں جیب میں رکھیں۔',
    ],
    azimatOrFormula: 'عقدت لسان کل ناطق بالسوء عنی بحق صم بکم عمی فہم لا ینطقون',
    protectionMeasures: ['سورہ فلق و ناس ۳-۳ بار پڑھیں۔'],
  },

  // ==========================================
  // SECTION 4: TASKHEER KHALAIQ & WJAHAAT
  // ==========================================
  {
    id: 'op-taskheer-khalaiq-shams',
    title: 'Grand Solar Prestige & Authority (Shams)',
    urduTitle: 'لوحِ شمسِ معظم برائے وجاہت، رعب و تسخیرِ حکام و امراء',
    purposeCategory: 'taskheer_khalaiq',
    purposeCategoryUrdu: 'تسخیر خلائق و وجاہت',
    targetStudio: 'naqsh',
    targetStudioNameUrdu: 'مولد النقوش و الواح',
    sourceBook: 'قوانین طلسم و شرفِ شمس (کاش البرنی)',
    author: 'کاش البرنی',
    severity: 'safe',
    severityUrdu: 'سعد اکبر و شرف',
    speed: 'seven_days',
    speedUrdu: 'پائیدار و دائمی',
    requiredSaat: 'ساعت شمس بوقتِ شرف شمس (۱۹ درجے حمل) یا اتوار طلوع آفتاب',
    suitableDay: 'اتوار',
    element: 'fire',
    elementUrdu: 'آتشی و نوری',
    incense: 'عود، زعفران، صندل سرخ، کافور',
    inkAndPaper: 'زعفران و مشک بر پترہ طلائی (سونے کا پترہ) یا زرد ریشمی کپڑا',
    direction: 'مشرق',
    defaultAdad: 1240,
    defaultText: 'یا عزیز یا معز یا رافع یا جلیل',
    summary: 'عوام الناس اور اعلیٰ حکام کے دلوں میں بے پناہ رعب، ہیبت، عزت، اور ہر دلعزیزی قائم کرنے کی شہرہ آفاق لوح۔',
    badge: 'شرفِ شمسِ معظم',
    preconditions: ['لباسِ فاخرہ، طہارتِ کامل، اور صدقہ زرد اشیاء بوقتِ اتوار۔'],
    steps: [
      '1. اپنے نام مع والدہ اور اسمائے الٰہی کے اعداد جمع کریں۔',
      '2. نقش مسدس ۶x۶ یا نقش معظم شمس آتشی چال سے تیار کریں۔',
      '3. پشت پر خاتمِ سلیمانی اور ملائکہ نورانی کندہ کریں۔',
      '4. دائیں بازو پر باندھیں یا گلے میں حمائل کریں۔',
    ],
    azimatOrFormula: 'اللہم البسنی مہابۃ منک و وقارا فی اعین خلقک یا ذالجلال والاکرام',
    protectionMeasures: ['روزانہ بعد نماز فجر ۱۰۰ بار یا عزیز یا معز کا ورد۔'],
  },

  // ==========================================
  // SECTION 5: TASKHEER JINN & ARWAH
  // ==========================================
  {
    id: 'op-taskheer-jinn-chilla',
    title: 'Spiritual Entities Chilla & Protective Mandal',
    urduTitle: 'قواعد ریاضتِ جفر، تسخیرِ اعوان و حصارِ منیع (مفتاح الجفر)',
    purposeCategory: 'taskheer_jinn_arwah',
    purposeCategoryUrdu: 'تسخیر جنات و ارواح',
    targetStudio: 'jafr-symbolism',
    targetStudioNameUrdu: 'تحقیقِ رموز و اشاراتِ جفر (کاش البرنی)',
    sourceBook: 'مفتاح الجفر و ریاضاتِ ارواح',
    author: 'کاش البرنی و ابو ریحان البیرونی',
    severity: 'caution',
    severityUrdu: 'محتاط (محتاجِ اجازتِ استاد)',
    speed: 'seven_days',
    speedUrdu: 'چلہ ۲۱ تا ۴۰ روز',
    requiredSaat: 'ساعت مشتری در نوچندی جمعرات',
    suitableDay: 'جمعرات',
    element: 'air',
    elementUrdu: 'لطیف و ہوائی',
    incense: 'لوبان ذکر، کندر، جاوا',
    inkAndPaper: 'کالی سیاہی برائے مندل، زعفران برائے عزیمت',
    direction: 'قبلہ رخ در خلوت گاہ',
    defaultAdad: 1111,
    defaultText: 'عزیمت برہتیہ و استخراج اعوان',
    summary: 'باطنی انکشاف، موکلین کے ناموں کا استخراج اور چلے کے دوران خوف و رجعت سے محفوظ رہنے کے ضوابط۔',
    badge: 'ریاضتِ خلوت',
    preconditions: [
      'پرہیز جلالی و جمالی کامل۔',
      'استادِ کامل کا اذن اور روحانی بیعت۔',
    ],
    steps: [
      '1. خلوت گاہ میں فولادی چھری سے آیت الکرسی کا مندل قائم کریں۔',
      '2. اسم اعظم اور حروفِ نورانی کا معین تعداد میں ورد کریں۔',
      '3. جب علاماتِ کشف ظاہر ہوں تو بغیر ہچکچاہٹ سلام کا جواب دیں۔',
    ],
    azimatOrFormula: 'برہتیہ ۲ کریر ۲ تاتلیہ ۲ طوران ۲ مزجل ۲ بزجل ۲ ترقب ۲ برہش ۲',
    protectionMeasures: ['حصار اعظم اور سورہ یٰس کا دائرہ۔'],
  },

  // ==========================================
  // SECTION 6: SHIFA & TIBB-E-JAFR
  // ==========================================
  {
    id: 'op-shifa-asqam-sarbaazi',
    title: 'Shifa Al-Asqam Divine Healing Formulations',
    urduTitle: 'علاجِ امراضِ خبیثہ و اسقامِ باطنیہ (مولانا محمد عمر سربازیؒ)',
    purposeCategory: 'shifa_amraz',
    purposeCategoryUrdu: 'شفا و علاجِ امراض',
    targetStudio: 'shifa-al-asqam',
    targetStudioNameUrdu: 'شفاء الاسقام والاحزان (مولانا سربازیؒ)',
    sourceBook: 'شفاء الاسقام والاحزان فی طب الروحانی والابدان',
    author: 'مولانا محمد عمر سربازیؒ',
    severity: 'safe',
    severityUrdu: 'خیر و شفا مطلق',
    speed: 'three_days',
    speedUrdu: '۳ تا ۷ یوم',
    requiredSaat: 'ساعت شمس یا زہرہ بعد از فجر',
    suitableDay: 'جمعہ / پیر',
    element: 'water',
    elementUrdu: 'آبی و مائی',
    incense: 'حرمل، کلونجی، لوبان',
    inkAndPaper: 'زعفران بر چینی کی پلیٹ یا عرقِ گلاب',
    direction: 'قبلہ رخ',
    defaultAdad: 391,
    defaultText: 'یا شافی یا کافی یا معافی شفا امراض',
    summary: 'لاعلاج امراض، سحر زدگی کی جسمانی بیماریاں، اور دائمی دردوں سے شفا کے لیے قرآنی و نبوی نقوش۔',
    badge: 'شفاء الاسقام سربازیؒ',
    preconditions: ['پاک صاف باوضو ہو کر پانی پر دم کرنا اور مریض کو پلانا۔'],
    steps: [
      '1. آیاتِ شفا (۶ آیاتِ قرآنیہ) اور اسم "یا شافی" کے اعداد کا نقش تیار کریں۔',
      '2. چینی کی سفید پلیٹ پر زعفران سے لکھ کر عرق گلاب سے دھو کر مریض کو نہار منہ پلائیں۔',
      '3. کلونجی اور زیتون کے تیل پر ۷۰ بار سورہ فاتحہ دم کر کے مالش کریں۔',
    ],
    azimatOrFormula: 'وَإِذَا مَرِضْتُ فَهُوَ يَشْفِينِ، وَنُنَزِّلُ مِنَ الْقُرْآنِ مَا هُوَ شِفَاءٌ وَرَحْمَةٌ لِّلْمُؤْمِنِينَ',
    protectionMeasures: ['صدقہ برائے مریض اور کثرتِ استغفار۔'],
  },

  // ==========================================
  // SECTION 7: IBTAL-E-SIHR & EVIL EYE
  // ==========================================
  {
    id: 'op-ibtal-sihr-qati',
    title: 'Definitive Neutralization of Black Magic & Curses',
    urduTitle: 'ابطالِ سحرِ اسود، ردِ سحر و دفعِ نظرِ بد (طلسماتِ کبار)',
    purposeCategory: 'ibtal_sihr_asib',
    purposeCategoryUrdu: 'ابطالِ سحر و دفعِ نظرِ بد',
    targetStudio: 'hisar',
    targetStudioNameUrdu: 'حصار اعظم و پرہیز',
    sourceBook: 'شفاء الاسقام و قوانین طلسم',
    author: 'جامع کتبِ جفر',
    severity: 'safe',
    severityUrdu: 'دافعِ شر و قاطعِ سحر',
    speed: 'instant',
    speedUrdu: 'فوری تا ۳ دن',
    requiredSaat: 'ساعت شمس یا مریخ بوقتِ اذانِ فجر',
    suitableDay: 'اتوار یا منگل',
    element: 'fire',
    elementUrdu: 'آتشی و آبی',
    incense: 'حرمل، کافور، نمک، سرسوں',
    inkAndPaper: 'زعفران و کالی سیاہی بر سفید کاغذ',
    direction: 'قبلہ رخ',
    defaultAdad: 818,
    defaultText: 'قال موسی ما جئتم بہ السحر ان اللہ سیبطلہ',
    summary: 'ہر قسم کے جادو، سفلی بندش، آسیب اور شیطانی اثرات کو فورا کاٹ کر جادوگر کی طرف واپس پلٹنے کا عمل۔',
    badge: 'قاطعِ سحرِ اسود',
    preconditions: ['مریض کو پاک پانی سے غسل دینا اور گھر کے کونوں میں دم شدہ پانی چھڑکنا۔'],
    steps: [
      '1. آیتِ ابطالِ سحر (سورہ یونس: ۸۱) اور معوذتین ۷۰ بار پڑھ کر پانی پر دم کریں۔',
      '2. نقشِ ابطالِ سحر تیار کر کے موم جامہ کر کے مریض کے گلے میں ڈالیں۔',
      '3. شام کے وقت حرمل اور نمک کی دھونی پورے گھر میں دیں۔',
    ],
    azimatOrFormula: 'فَوَقَعَ الْحَقُّ وَبَطَلَ مَا كَانُوا يَعْمَلُونَ، إِنَّ اللَّهَ سَيُبْطِلُهُ إِنَّ اللَّهَ لَا يُصْلِحُ عَمَلَ الْمُفْسِدِينَ',
    protectionMeasures: ['روزانہ صبح و شام منزل شریف کا ورد۔'],
  },

  // ==========================================
  // SECTION 8: RIZQ & BARKAT
  // ==========================================
  {
    id: 'op-rizq-tijarat-bistat',
    title: 'Abundance of Wealth & Business Expansion',
    urduTitle: 'لوحِ وسعتِ رزق، کشائشِ کار و برکتِ تجارت (مفتاح الجفر)',
    purposeCategory: 'rizq_tijarat',
    purposeCategoryUrdu: 'وسعتِ رزق و تجارت',
    targetStudio: 'naqsh',
    targetStudioNameUrdu: 'مولد النقوش و الواح',
    sourceBook: 'مفتاح الجفر و شمس المعارف',
    author: 'کاش البرنی و البونیؒ',
    severity: 'safe',
    severityUrdu: 'سعد و پر برکت',
    speed: 'seven_days',
    speedUrdu: 'پائیدار و مسلسل',
    requiredSaat: 'ساعت مشتری (جمعرات اول ساعت)',
    suitableDay: 'جمعرات',
    element: 'earth',
    elementUrdu: 'ترابی و ہوائی',
    incense: 'صندل سفید، لوبان، جاوتری',
    inkAndPaper: 'زعفران و عرق گلاب بر زرد کاغذ یا چاندی کی تختی',
    direction: 'مشرق',
    defaultAdad: 308,
    defaultText: 'یا رزاق یا فتاح یا باسط یا غنی',
    summary: 'دکان و کاروبار میں گاہکوں کا ہجوم، بندشِ رزق کا خاتمہ اور فقر و تنگدستی کو غنا میں بدلنے کا عمل۔',
    badge: 'اکسیرِ رزق و برکت',
    preconditions: ['حلال رزق کی نیت اور کمائی سے باقاعدہ عشر و صدقہ نکالنے کا عہد۔'],
    steps: [
      '1. سورہ واقعہ اور اسمائے رزق کے کل اعداد نکال کر نقش مخمس تیار کریں۔',
      '2. نقش کو دکان یا تجارتی مقام کے دروازے کے اوپر آویزاں کریں۔',
      '3. روزانہ ۳۰۸ بار "یا رزاق یا فتاح" کا ورد کریں۔',
    ],
    azimatOrFormula: 'اللہم یا غنی یا مغنی یا باسط یا وہاب ارزقنی رزقا واسعا حلالا طیبا مبارکا فیہ',
    protectionMeasures: ['نمازِ پنجگانہ کی پابندی۔'],
  },

  // ==========================================
  // SECTION 9: KASHF & ISTIKHARA
  // ==========================================
  {
    id: 'op-kashf-khwab-albiruni',
    title: 'Clairvoyance & Dream Vision of Hidden Matters',
    urduTitle: 'کشفِ منامات و کشائشِ اسرارِ غائب (کتاب التفهیم للبیرونی)',
    purposeCategory: 'kashf_istikhara',
    purposeCategoryUrdu: 'کشف، خواب و استخارہ',
    targetStudio: 'istikhara',
    targetStudioNameUrdu: 'استخارہ و تعبیرِ خواب',
    sourceBook: 'کتاب التفهیم و رموز الجفر',
    author: 'ابو ریحان البیرونی و کاش البرنی',
    severity: 'safe',
    severityUrdu: 'نورانی و روحانی',
    speed: 'one_night',
    speedUrdu: 'شبِ واحد (خواب میں)',
    requiredSaat: 'ساعت قمر قبل از خواب',
    suitableDay: 'دوشنبہ (پیر) یا جمعرات',
    element: 'water',
    elementUrdu: 'آبی و لطیف',
    incense: 'عود، کافور',
    inkAndPaper: 'عرق گلاب بر کفِ دست (ہتھیلی) یا سفید کاغذ',
    direction: 'قبلہ رخ روبہ بستر',
    defaultAdad: 1040,
    defaultText: 'یا علیم یا خبیر ارنی فی منامی کذا و کذا',
    summary: 'خواب میں گمشدہ شے، مستقبل کے فیصلے یا پوشیدہ حقیقت کا صاف صاف مشاہدہ کرنے کا طریقہ۔',
    badge: 'کشفِ منامِ صادق',
    preconditions: ['باوضو سونا، دائیں کروٹ لیٹنا، اور سونے سے قبل غیر ضروری گفتگو سے بچنا۔'],
    steps: [
      '1. اسم "یا علیم یا خبیر یا مبین" کو ۲۵۶ بار پڑھ کر دل پر دم کریں۔',
      '2. دائیں ہتھیلی پر حرف "ط" اور "ع" لکھ کر سو جائیں۔',
    ],
    azimatOrFormula: 'اللہم ارنی فی منامی بیانا شافیا عما سألتک عنہ بحق اسمک العلیم الخبیر',
    protectionMeasures: ['سوتے وقت معوذتین پڑھنا۔'],
  },

  // ==========================================
  // SECTION 10: HISAR-E-AZAM & PROTECTION
  // ==========================================
  {
    id: 'op-hisar-sulaimani-azamat',
    title: 'Invincible Solomon Steel Armor & Fortress',
    urduTitle: 'حصارِ اعظم، خاتمِ سلیمانی و دائرۂ فولادی برہتیہ',
    purposeCategory: 'hisar_hifazat',
    purposeCategoryUrdu: 'حصارِ اعظم و حفاظت',
    targetStudio: 'hisar',
    targetStudioNameUrdu: 'حصار اعظم و پرہیز',
    sourceBook: 'قوانین طلسم و کشکولِ کاش البرنی',
    author: 'کاش البرنی',
    severity: 'safe',
    severityUrdu: 'حفاظتِ تامہ و قلعہ',
    speed: 'instant',
    speedUrdu: 'دائمی و فوری',
    requiredSaat: 'کسی بھی وقت (خصوصاً قبل از عمل)',
    suitableDay: 'ہر دن',
    element: 'earth',
    elementUrdu: 'فولادی و ناری',
    incense: 'لوبان، حرمل',
    inkAndPaper: 'کالی روشنائی بر لوحِ آہن (لوہا) یا کاغذ',
    direction: 'چاروں اطراف',
    defaultAdad: 66,
    defaultText: 'حصار آیت الکرسی و خاتم سلیمان',
    summary: 'عامل کے گرد ایسا روحانی قلعہ جو دشمن کے تیر، جادوگر کے جادو اور رجعت کے اثرات کو پرکاہ کے برابر بھی اثر نہیں کرنے دیتا۔',
    badge: 'حصارِ فولادی',
    preconditions: ['طہارت، یقینِ کامل، اور نیتِ حفاظتِ خود و عیال۔'],
    steps: [
      '1. انگشتِ شہادت سے اپنے گرد فرضی دائرہ کھینچتے ہوئے آیت الکرسی پڑھیں۔',
      '2. چاروں قل اور اسمائے شواذِ سبعہ (ف ج ش ث ظ خ ز) پر دم کریں۔',
      '3. لوحِ حصار کو اپنے گلے یا بٹوے میں محفوظ رکھیں۔',
    ],
    azimatOrFormula: 'حَصَّنْتُ نَفْسِي بِالْحَيِّ الْقَيُّومِ الَّذِي لَا يَمُوتُ أَبَدًا وَدَفَعْتُ عَنِّي السُّوءَ بِلَا حَوْلَ وَلَا قُوَّةَ إِلَّا بِاللَّهِ الْعَلِيِّ الْعَظِيمِ',
    protectionMeasures: ['صبح و شام ۳ بار دعائے حصار۔'],
  },
];
